// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vrename_test_top.h for the primary calling header

#ifndef VERILATED_VRENAME_TEST_TOP___024ROOT_H_
#define VERILATED_VRENAME_TEST_TOP___024ROOT_H_  // guard

#include "verilated.h"


class Vrename_test_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vrename_test_top___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_IN8(in_valid,1,0);
        VL_IN8(in_lsrc1_0,4,0);
        VL_IN8(in_lsrc2_0,4,0);
        VL_IN8(in_ldst_0,4,0);
        VL_IN8(in_br_mask_0,3,0);
        VL_IN8(in_lsrc1_1,4,0);
        VL_IN8(in_lsrc2_1,4,0);
        VL_IN8(in_ldst_1,4,0);
        VL_IN8(in_br_mask_1,3,0);
        VL_IN8(in_allocate_brtag_0,0,0);
        VL_IN8(in_br_tag_0,1,0);
        VL_IN8(in_allocate_brtag_1,0,0);
        VL_IN8(in_br_tag_1,1,0);
        VL_IN8(wakeup_valid,0,0);
        VL_IN8(wakeup_pdst,5,0);
        VL_IN8(commit_valid,0,0);
        VL_IN8(commit_ldst,4,0);
        VL_IN8(commit_pdst,5,0);
        VL_IN8(commit_stale_pdst,5,0);
        VL_IN8(rollback,0,0);
        VL_IN8(kill,0,0);
        VL_IN8(br_mispredict,0,0);
        VL_IN8(br_mispredict_tag,1,0);
        VL_IN8(br_resolve_mask,3,0);
        VL_IN8(br_mispredict_mask,3,0);
        VL_IN8(dis_ready,0,0);
        VL_IN8(dis_fire,1,0);
        VL_OUT8(out_valid,1,0);
        VL_OUT8(out_psrc1_0,5,0);
        VL_OUT8(out_psrc2_0,5,0);
        VL_OUT8(out_pdst_0,5,0);
        VL_OUT8(out_stale_0,5,0);
        VL_OUT8(out_psrc1_busy_0,0,0);
        VL_OUT8(out_psrc1_1,5,0);
        VL_OUT8(out_psrc2_1,5,0);
        VL_OUT8(out_pdst_1,5,0);
        VL_OUT8(out_stale_1,5,0);
        VL_OUT8(out_psrc1_busy_1,0,0);
        VL_OUT8(out_br_mask_0,3,0);
        VL_OUT8(out_br_mask_1,3,0);
        VL_OUT8(stalls,1,0);
        CData/*1:0*/ rename_test_top__DOT__dut__DOT__mt_write_en;
        SData/*9:0*/ rename_test_top__DOT__dut__DOT__mt_write_lreg;
        SData/*11:0*/ rename_test_top__DOT__dut__DOT__mt_write_preg;
        SData/*9:0*/ rename_test_top__DOT__dut__DOT__mt_commit_lreg;
        SData/*11:0*/ rename_test_top__DOT__dut__DOT__mt_commit_preg;
        CData/*1:0*/ rename_test_top__DOT__dut__DOT__br_snapshot_en;
        CData/*3:0*/ rename_test_top__DOT__dut__DOT__br_snapshot_tag;
        CData/*1:0*/ rename_test_top__DOT__dut__DOT__fl_free_en;
        SData/*11:0*/ rename_test_top__DOT__dut__DOT__fl_free_preg;
        CData/*1:0*/ rename_test_top__DOT__dut__DOT__rn2_mask_q;
        CData/*1:0*/ rename_test_top__DOT__dut__DOT__rn2_mask_next;
        CData/*7:0*/ __VdfgRegularize_h6e95ff9d_0_2;
        CData/*7:0*/ __VdfgRegularize_h6e95ff9d_0_3;
        CData/*7:0*/ __VdfgRegularize_h6e95ff9d_0_4;
        CData/*7:0*/ __VdfgRegularize_h6e95ff9d_0_5;
        CData/*7:0*/ __VdfgRegularize_h6e95ff9d_0_6;
        CData/*7:0*/ __VdfgRegularize_h6e95ff9d_0_8;
        CData/*7:0*/ __VdfgRegularize_h6e95ff9d_0_9;
        CData/*6:0*/ __VdfgRegularize_h6e95ff9d_0_10;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_19;
        CData/*5:0*/ __VdfgRegularize_h6e95ff9d_0_20;
    };
    struct {
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_24;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_25;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_26;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_29;
        CData/*6:0*/ __VdfgRegularize_h6e95ff9d_0_30;
        CData/*6:0*/ __VdfgRegularize_h6e95ff9d_0_31;
        CData/*5:0*/ __VdfgRegularize_h6e95ff9d_0_33;
        CData/*5:0*/ __VdfgRegularize_h6e95ff9d_0_34;
        CData/*5:0*/ __VdfgRegularize_h6e95ff9d_0_35;
        CData/*5:0*/ __VdfgRegularize_h6e95ff9d_0_36;
        CData/*5:0*/ __VdfgRegularize_h6e95ff9d_0_37;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_38;
        CData/*1:0*/ __VdfgRegularize_h6e95ff9d_0_40;
        CData/*1:0*/ __VdfgRegularize_h6e95ff9d_0_43;
        CData/*3:0*/ __VdfgRegularize_h6e95ff9d_0_45;
        CData/*1:0*/ __VdfgRegularize_h6e95ff9d_0_46;
        CData/*1:0*/ __VdfgRegularize_h6e95ff9d_0_47;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_48;
        CData/*5:0*/ __VdfgRegularize_h6e95ff9d_0_49;
        CData/*0:0*/ __VdlySet__rename_test_top__DOT__dut__DOT__freelist__DOT__br_alloc_q__v0;
        CData/*0:0*/ __VdlySet__rename_test_top__DOT__dut__DOT__freelist__DOT__br_alloc_q__v4;
        CData/*1:0*/ __VdlyDim0__rename_test_top__DOT__dut__DOT__freelist__DOT__br_alloc_q__v8;
        CData/*0:0*/ __VdlySet__rename_test_top__DOT__dut__DOT__freelist__DOT__br_alloc_q__v8;
        CData/*1:0*/ __VdlyDim0__rename_test_top__DOT__dut__DOT__freelist__DOT__br_alloc_q__v9;
        CData/*0:0*/ __VdlySet__rename_test_top__DOT__dut__DOT__freelist__DOT__br_alloc_q__v9;
        CData/*0:0*/ __VdlySet__rename_test_top__DOT__dut__DOT__freelist__DOT__br_alloc_q__v10;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v0;
        CData/*0:0*/ __VdlySet__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v0;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v1;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v2;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v3;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v4;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v5;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v6;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v7;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v8;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v9;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v10;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v11;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v12;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v13;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v14;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v15;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v16;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v17;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v18;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v19;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v20;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v21;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v22;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v23;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v24;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v25;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v26;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v27;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v28;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v29;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v30;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v31;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v32;
        CData/*0:0*/ __VdlySet__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v32;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v33;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v34;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v35;
    };
    struct {
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v36;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v37;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v38;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v39;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v40;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v41;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v42;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v43;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v44;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v45;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v46;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v47;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v48;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v49;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v50;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v51;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v52;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v53;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v54;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v55;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v56;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v57;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v58;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v59;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v60;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v61;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v62;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v63;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v64;
        CData/*0:0*/ __VdlySet__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v64;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v65;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v66;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v67;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v68;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v69;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v70;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v71;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v72;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v73;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v74;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v75;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v76;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v77;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v78;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v79;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v80;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v81;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v82;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v83;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v84;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v85;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v86;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v87;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v88;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v89;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v90;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v91;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v92;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v93;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v94;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v95;
        CData/*0:0*/ __VdlySet__rename_test_top__DOT__dut__DOT__maptable__DOT__map_q__v96;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v0;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v0;
    };
    struct {
        CData/*0:0*/ __VdlySet__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v0;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v1;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v1;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v2;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v2;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v3;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v3;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v4;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v4;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v5;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v5;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v6;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v6;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v7;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v7;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v8;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v8;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v9;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v9;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v10;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v10;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v11;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v11;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v12;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v12;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v13;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v13;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v14;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v14;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v15;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v15;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v16;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v16;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v17;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v17;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v18;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v18;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v19;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v19;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v20;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v20;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v21;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v21;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v22;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v22;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v23;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v23;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v24;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v24;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v25;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v25;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v26;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v26;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v27;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v27;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v28;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v28;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v29;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v29;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v30;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v30;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v31;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v31;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v32;
    };
    struct {
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v32;
        CData/*0:0*/ __VdlySet__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v32;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v33;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v33;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v34;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v34;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v35;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v35;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v36;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v36;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v37;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v37;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v38;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v38;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v39;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v39;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v40;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v40;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v41;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v41;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v42;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v42;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v43;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v43;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v44;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v44;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v45;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v45;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v46;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v46;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v47;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v47;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v48;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v48;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v49;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v49;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v50;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v50;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v51;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v51;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v52;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v52;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v53;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v53;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v54;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v54;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v55;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v55;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v56;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v56;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v57;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v57;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v58;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v58;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v59;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v59;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v60;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v60;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v61;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v61;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v62;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v62;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v63;
        CData/*1:0*/ __VdlyDim1__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v63;
    };
    struct {
        CData/*0:0*/ __VdlySet__rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q__v64;
        CData/*5:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__maptable__DOT__commit_map_q__v0;
        CData/*4:0*/ __VdlyDim0__rename_test_top__DOT__dut__DOT__maptable__DOT__commit_map_q__v0;
        CData/*0:0*/ __VdlySet__rename_test_top__DOT__dut__DOT__maptable__DOT__commit_map_q__v0;
        CData/*0:0*/ __VdlySet__rename_test_top__DOT__dut__DOT__maptable__DOT__commit_map_q__v1;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_n__0;
        CData/*1:0*/ __Vtrigprevexpr___TOP__in_valid__0;
        CData/*4:0*/ __Vtrigprevexpr___TOP__in_lsrc1_0__0;
        CData/*4:0*/ __Vtrigprevexpr___TOP__in_lsrc2_0__0;
        CData/*4:0*/ __Vtrigprevexpr___TOP__in_ldst_0__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__in_br_mask_0__0;
        CData/*4:0*/ __Vtrigprevexpr___TOP__in_lsrc1_1__0;
        CData/*4:0*/ __Vtrigprevexpr___TOP__in_lsrc2_1__0;
        CData/*4:0*/ __Vtrigprevexpr___TOP__in_ldst_1__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__in_br_mask_1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__in_allocate_brtag_0__0;
        CData/*1:0*/ __Vtrigprevexpr___TOP__in_br_tag_0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__in_allocate_brtag_1__0;
        CData/*1:0*/ __Vtrigprevexpr___TOP__in_br_tag_1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__wakeup_valid__0;
        CData/*5:0*/ __Vtrigprevexpr___TOP__wakeup_pdst__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__commit_valid__0;
        CData/*4:0*/ __Vtrigprevexpr___TOP__commit_ldst__0;
        CData/*5:0*/ __Vtrigprevexpr___TOP__commit_pdst__0;
        CData/*5:0*/ __Vtrigprevexpr___TOP__commit_stale_pdst__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rollback__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__kill__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__br_mispredict__0;
        CData/*1:0*/ __Vtrigprevexpr___TOP__br_mispredict_tag__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__br_resolve_mask__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__br_mispredict_mask__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__dis_ready__0;
        CData/*1:0*/ __Vtrigprevexpr___TOP__dis_fire__0;
        CData/*0:0*/ __VicoDidInit;
        CData/*0:0*/ __VicoPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_n__1;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        SData/*14:0*/ __VdfgRegularize_h6e95ff9d_0_27;
        SData/*11:0*/ __VdfgRegularize_h6e95ff9d_0_39;
        SData/*9:0*/ __VdfgRegularize_h6e95ff9d_0_41;
        SData/*11:0*/ __VdfgRegularize_h6e95ff9d_0_44;
        IData/*29:0*/ __VdfgRegularize_h6e95ff9d_0_23;
        IData/*31:0*/ __VactIterCount;
        VlWide<16>/*496:0*/ rename_test_top__DOT__brupdate;
        QData/*55:0*/ rename_test_top__DOT__dut__DOT__mt_arch_busy_vec;
        VlWide<26>/*831:0*/ rename_test_top__DOT__dut__DOT__rn2_uops_q;
        VlWide<26>/*831:0*/ rename_test_top__DOT__dut__DOT__rn2_uops_next;
        QData/*55:0*/ rename_test_top__DOT__dut__DOT__busytable__DOT__busy_vec;
        VlWide<6>/*167:0*/ rename_test_top__DOT__dut__DOT__freelist__DOT__alloc_suffix;
        QData/*55:0*/ rename_test_top__DOT__dut__DOT__freelist__DOT__alloc_mask_all;
        QData/*55:0*/ rename_test_top__DOT__dut__DOT__freelist__DOT__commit_free_mask;
        QData/*55:0*/ rename_test_top__DOT__dut__DOT__freelist__DOT__br_free_mask;
        QData/*55:0*/ rename_test_top__DOT__dut__DOT__freelist__DOT__free_vec_next;
        QData/*55:0*/ rename_test_top__DOT__dut__DOT__freelist__DOT__free_vec;
        VlWide<4>/*111:0*/ rename_test_top__DOT__dut__DOT__freelist__DOT__alloc_pick;
        QData/*55:0*/ __VdfgRegularize_h6e95ff9d_0_0;
        QData/*55:0*/ __VdfgRegularize_h6e95ff9d_0_12;
        QData/*55:0*/ __VdfgRegularize_h6e95ff9d_0_13;
        QData/*37:0*/ __VdfgRegularize_h6e95ff9d_0_21;
    };
    struct {
        QData/*37:0*/ __VdfgRegularize_h6e95ff9d_0_22;
        QData/*35:0*/ __VdfgRegularize_h6e95ff9d_0_28;
        QData/*55:0*/ __VdfgRegularize_h6e95ff9d_0_32;
        QData/*55:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__freelist__DOT__br_alloc_q__v4;
        QData/*55:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__freelist__DOT__br_alloc_q__v5;
        QData/*55:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__freelist__DOT__br_alloc_q__v6;
        QData/*55:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__freelist__DOT__br_alloc_q__v7;
        QData/*55:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__freelist__DOT__br_alloc_q__v8;
        QData/*55:0*/ __VdlyVal__rename_test_top__DOT__dut__DOT__freelist__DOT__br_alloc_q__v9;
        VlUnpacked<QData/*55:0*/, 4> rename_test_top__DOT__dut__DOT__freelist__DOT__br_alloc_q;
        VlUnpacked<QData/*55:0*/, 2> rename_test_top__DOT__dut__DOT__freelist__DOT__alloc_mask;
        VlUnpacked<CData/*5:0*/, 32> rename_test_top__DOT__dut__DOT__maptable__DOT__map_q;
        VlUnpacked<CData/*5:0*/, 32> rename_test_top__DOT__dut__DOT__maptable__DOT__commit_map_q;
        VlUnpacked<VlUnpacked<CData/*5:0*/, 32>, 4> rename_test_top__DOT__dut__DOT__maptable__DOT__br_snapshot_q;
        VlUnpacked<VlUnpacked<CData/*5:0*/, 32>, 3> rename_test_top__DOT__dut__DOT__maptable__DOT__map_after_lane;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 2> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };

    // INTERNAL VARIABLES
    Vrename_test_top__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vrename_test_top___024root(Vrename_test_top__Syms* symsp, const char* namep);
    ~Vrename_test_top___024root();
    VL_UNCOPYABLE(Vrename_test_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
