// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vcore_top_contract_test_top.h for the primary calling header

#ifndef VERILATED_VCORE_TOP_CONTRACT_TEST_TOP___024ROOT_H_
#define VERILATED_VCORE_TOP_CONTRACT_TEST_TOP___024ROOT_H_  // guard

#include "verilated.h"
#include "Vcore_top_contract_test_top_loom_types.h"


class Vcore_top_contract_test_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vcore_top_contract_test_top___024root final {
  public:
    // CELLS
    Vcore_top_contract_test_top_loom_types* __PVT__loom_types;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_OUT8(imem_req_valid,0,0);
        VL_IN8(imem_req_ready,0,0);
        VL_IN8(imem_resp_valid,0,0);
        VL_OUT8(imem_resp_ready,0,0);
        VL_OUT8(dmem_req_valid,0,0);
        VL_IN8(dmem_req_ready,0,0);
        VL_OUT8(dmem_req_is_store,0,0);
        VL_OUT8(dmem_req_mask,3,0);
        VL_OUT8(dmem_req_size,1,0);
        VL_OUT8(dmem_req_idx,5,0);
        VL_IN8(dmem_resp_valid,0,0);
        VL_IN8(dmem_resp_is_store,0,0);
        VL_IN8(dmem_resp_idx,5,0);
        VL_IN8(hw_irq,7,0);
        VL_IN8(ipi_irq,0,0);
        VL_OUT8(commit_valid,1,0);
        VL_OUT16(commit_ldst,9,0);
        VL_OUT8(exception_valid,0,0);
        CData/*3:0*/ core_top_contract_test_top__DOT__dut__DOT__ifu_fetch_valid;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__ifu_fetch_ready;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__buffer_deq_valid;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__buffer_deq_ready;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core_redirect_valid;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_req_valid;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_empty;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__dec_fire;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unique_dispatch_ready;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__fe_finished_q;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__fe_completed;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__iq_mem_dis_valid;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__iq_alu_dis_valid;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__iq_unq_dis_valid;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__alu_iq_dis_ready;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__mem_iq_dis_ready;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_iq_dis_ready;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rn2_mask;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__dis_fire;
        CData/*7:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rn2_iq_type_q;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rn2_exception_q;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rn2_unique_q;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rn2_uses_ldq_q;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rn2_uses_stq_q;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_req_ready_w;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_ertn_valid_w;
        CData/*7:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__bm_br_mask;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__bm_flush;
        CData/*2:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__alu_iss_valid;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__mem_iss_valid__BRA__0__KET__;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rf_write_en;
        IData/*29:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rf_write_addr;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__alu_wakeup_valid__BRA__2__KET__;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__alu_wakeup_valid__BRA__1__KET__;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__alu_wakeup_valid__BRA__0__KET__;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_clr_bsy_valid;
        SData/*11:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_clr_bsy_rob_idx;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_load_wb_valid;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_res_valid;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_exec_ready;
        CData/*5:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_tail_idx_w;
        CData/*5:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_head_idx_w;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT____Vcellinp__rob_inst__enq_partial_stall;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT____Vcellout__gen_alu__BRA__0__KET____DOT__alu_inst__res_valid;
    };
    struct {
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT____Vcellout__gen_alu__BRA__1__KET____DOT__alu_inst__res_valid;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT____Vcellout__gen_alu__BRA__2__KET____DOT__alu_inst__res_valid;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT____Vcellout__gen_mem__BRA__0__KET____DOT__mem_inst__agen_valid;
        CData/*2:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__state;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__busy_cnt;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__busy_done;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__pipe_br_killed;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__issue_fire;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__div_req_ready;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__div_req_signed;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT____Vcellinp__divider_i__kill;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__quotient_negate_q;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__remainder_negate_q;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__select_remainder_q;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__divisor_zero_q;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__state;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__iteration_count_q;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__iteration_index_q;
        CData/*5:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__recovery_shift_q;
        CData/*2:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__quotient_digit;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__otfc_clear;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__otfc_step;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__req_fire;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__resp_fire;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__mt_write_en;
        SData/*9:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__mt_write_lreg;
        SData/*11:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__mt_write_preg;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__mt_commit_en;
        SData/*9:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__mt_commit_lreg;
        SData/*11:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__mt_commit_preg;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__br_snapshot_en;
        CData/*3:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__br_snapshot_tag;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__fl_free_en;
        SData/*11:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__fl_free_preg;
        CData/*5:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__bt_wakeup_en;
        QData/*35:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__bt_wakeup_preg;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__rn2_mask_q;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__rn2_mask_next;
        CData/*5:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT____VlemCall_0__priority_encoder;
        SData/*11:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT__alloc_cand;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__ldq_enq_valid;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__ldq_enq_fire;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__ldq_enq_ready;
        SData/*11:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__ldq_enq_idx;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__stq_enq_valid;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__stq_enq_fire;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__stq_enq_ready;
        SData/*11:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__stq_enq_idx;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__ld_query_valid;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__ld_query_block;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__ld_query_forward_valid;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__ld_req_valid;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__st_req_valid;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__arb_locked;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__locked_is_store;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__prefer_store;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__next_gen;
        CData/*3:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__alloc_hint;
        CData/*7:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__enq_slot;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__enq_write;
        CData/*3:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__alloc_hint_next;
        CData/*7:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__clr_slot;
        VlWide<3>/*95:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__commit_fifo;
        CData/*3:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__cq_head;
    };
    struct {
        CData/*3:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__cq_tail;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__cq_count;
        CData/*7:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__commit_slot;
        CData/*7:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__cq_write_slot;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__commit_match;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__commit_push_count;
        CData/*3:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__cq_tail_next;
        CData/*5:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__cq_head_tag;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__req_hold_valid;
        CData/*5:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__req_hold_idx;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__req_hold_live;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__store_req_fire;
        CData/*3:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__ack_slot;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__ack_match;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__cq_count_next;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__agen_match;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__dgen_match;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__next_gen;
        CData/*3:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__alloc_hint;
        CData/*3:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__query_cursor;
        CData/*7:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__enq_slot;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__enq_write;
        CData/*3:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__alloc_hint_next;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__req_hold_valid;
        CData/*5:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__req_hold_idx;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__req_candidate_valid;
        CData/*3:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__req_candidate_slot;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__req_hold_live;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__req_hold_killed;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__dmem_req_fire;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__resp_match;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__fwd_hold_valid;
        CData/*5:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__fwd_hold_idx;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__fwd_hold_live;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__fwd_hold_killed;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__fwd_wb_fire;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__agen_match;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__iss_br_killed;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__rrd_valid;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__rrd_br_killed;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__exe_valid;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__iss_br_killed;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__rrd_valid;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__rrd_br_killed;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__exe_valid;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__iss_br_killed;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__rrd_valid;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__rrd_br_killed;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__exe_valid;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__iss_br_killed;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__rrd_valid;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__rrd_br_killed;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__exe_valid;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__timer_irq_q;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__timer_armed_q;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__pending_q;
        CData/*5:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__pending_rob_idx_q;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__pending_cmd_q;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__commit_match;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_26__priority_encoder;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_25__is_older;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_24__get_row;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_23__get_row;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_22__get_bank;
    };
    struct {
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_21__get_row;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_20__get_row;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_19__get_row;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_18__get_row;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_17__get_row;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_16__get_row;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_15__get_bank;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_14__is_older;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_13__get_row;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_12__get_row;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_11__get_bank;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_10__get_row;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_9__get_row;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_8__get_row;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_7__get_row;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_6__get_row;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_5__get_row;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_4__get_bank;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT____VlemCall_0__get_row;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__interrupt_taken;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_head;
        CData/*4:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_tail;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_head_lsb;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_tail_lsb;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_state;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_head_vals;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__lxcpt_live;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__can_throw_exception;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__will_commit;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__exception_throw;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__xcpt_bank;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__flush_commit_mask;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__exception_throw_d1;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__exception_throw_d2;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__finished_committing_row;
        CData/*7:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_iq__DOT__dis_slot;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_iq__DOT__dis_br_killed;
        CData/*7:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__mem_iq__DOT__dis_slot;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__mem_iq__DOT__dis_br_killed;
        CData/*7:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__alu_iq__DOT__dis_slot;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__alu_iq__DOT__dis_br_killed;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__dispatch_inst__DOT__block;
        CData/*3:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__brmask__DOT__br_mask_q;
        CData/*3:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__brmask__DOT__curr_mask;
        CData/*2:0*/ core_top_contract_test_top__DOT__dut__DOT__fetch_buffer__DOT____VlemCall_3__ptr_add;
        CData/*2:0*/ core_top_contract_test_top__DOT__dut__DOT__fetch_buffer__DOT____VlemCall_2__ptr_add;
        CData/*2:0*/ core_top_contract_test_top__DOT__dut__DOT__fetch_buffer__DOT__head_q;
        CData/*2:0*/ core_top_contract_test_top__DOT__dut__DOT__fetch_buffer__DOT__tail_q;
        CData/*3:0*/ core_top_contract_test_top__DOT__dut__DOT__fetch_buffer__DOT__count_q;
        CData/*2:0*/ core_top_contract_test_top__DOT__dut__DOT__fetch_buffer__DOT__enq_count;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__fetch_buffer__DOT__deq_count;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__fetch_buffer__DOT__enq_fire;
        CData/*1:0*/ core_top_contract_test_top__DOT__dut__DOT__frontend__DOT__state_q;
        CData/*0:0*/ core_top_contract_test_top__DOT__dut__DOT__frontend__DOT__request_stale_q;
        CData/*3:0*/ core_top_contract_test_top__DOT__dut__DOT__frontend__DOT__fetch_valid_q;
        CData/*1:0*/ __Vfunc_core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__align_store_data__26__size;
        CData/*1:0*/ __Vfunc_core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__align_store_data__26__byte_offset;
        CData/*0:0*/ __Vfunc_core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__priority_encoder__84__Vfuncout;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_4;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_5;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_6;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_7;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_38;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_39;
    };
    struct {
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_44;
        CData/*5:0*/ __VdfgRegularize_h6e95ff9d_0_45;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_52;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_59;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_71;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_72;
        CData/*1:0*/ __VdfgRegularize_h6e95ff9d_0_73;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_91;
        CData/*5:0*/ __VdfgRegularize_h6e95ff9d_0_94;
        CData/*5:0*/ __VdfgRegularize_h6e95ff9d_0_110;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_111;
        CData/*1:0*/ __VdfgRegularize_h6e95ff9d_0_112;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_114;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_115;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_116;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_128;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_129;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_137;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_146;
        CData/*3:0*/ __VdfgRegularize_h6e95ff9d_0_147;
        CData/*7:0*/ __VdfgRegularize_h6e95ff9d_0_151;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_158;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_159;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_160;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_161;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_162;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_163;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_164;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_165;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_166;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_167;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_168;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_169;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_170;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_171;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_172;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_173;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_174;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_175;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_176;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_177;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_178;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_179;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_180;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_181;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_182;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_183;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_184;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_185;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_186;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_187;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_188;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_189;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_190;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_196;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_197;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_199;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_203;
        CData/*5:0*/ __VdfgRegularize_h6e95ff9d_0_207;
        CData/*5:0*/ __VdfgRegularize_h6e95ff9d_0_208;
        CData/*5:0*/ __VdfgRegularize_h6e95ff9d_0_209;
        CData/*1:0*/ __VdfgRegularize_h6e95ff9d_0_210;
        CData/*1:0*/ __VdfgRegularize_h6e95ff9d_0_235;
        CData/*1:0*/ __VdfgRegularize_h6e95ff9d_0_236;
    };
    struct {
        CData/*1:0*/ __VdfgRegularize_h6e95ff9d_0_258;
        CData/*1:0*/ __VdfgRegularize_h6e95ff9d_0_261;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_267;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_269;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_270;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_271;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_272;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_273;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_274;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_275;
        CData/*2:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__state;
        CData/*1:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__state;
        CData/*4:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__iteration_count_q;
        CData/*4:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__iteration_index_q;
        CData/*5:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__recovery_shift_q;
        CData/*5:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__req_hold_idx;
        IData/*31:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__next_gen;
        CData/*0:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__req_hold_valid;
        CData/*0:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__fwd_hold_valid;
        CData/*5:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__req_hold_idx;
        CData/*5:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__fwd_hold_idx;
        IData/*31:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__next_gen;
        CData/*4:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_head;
        CData/*4:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_tail;
        CData/*1:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_state;
        CData/*2:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__fetch_buffer__DOT__tail_q;
        CData/*2:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__fetch_buffer__DOT__head_q;
        CData/*1:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__frontend__DOT__state_q;
        CData/*0:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__frontend__DOT__request_stale_q;
        CData/*3:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__frontend__DOT__fetch_valid_q;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT__br_alloc_q__v0;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT__br_alloc_q__v4;
        CData/*1:0*/ __VdlyDim0__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT__br_alloc_q__v8;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT__br_alloc_q__v8;
        CData/*1:0*/ __VdlyDim0__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT__br_alloc_q__v9;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT__br_alloc_q__v9;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT__br_alloc_q__v10;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__maptable__DOT__map_q__v0;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__maptable__DOT__map_q__v32;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__maptable__DOT__map_q__v64;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__maptable__DOT__map_q__v96;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__maptable__DOT__br_snapshot_q__v0;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__maptable__DOT__br_snapshot_q__v32;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__maptable__DOT__br_snapshot_q__v64;
        CData/*5:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__maptable__DOT__commit_map_q__v0;
        CData/*4:0*/ __VdlyDim0__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__maptable__DOT__commit_map_q__v0;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__maptable__DOT__commit_map_q__v0;
        CData/*5:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__maptable__DOT__commit_map_q__v1;
        CData/*4:0*/ __VdlyDim0__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__maptable__DOT__commit_map_q__v1;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__maptable__DOT__commit_map_q__v1;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__maptable__DOT__commit_map_q__v2;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__save_q__v0;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__save_q__v1;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__save_q__v2;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__save_q__v3;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__save_q__v4;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__save_q__v5;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_cause__v0;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_cause__v1;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_cause__v2;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_uop__v0;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v0;
        CData/*0:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v0;
        CData/*4:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v0;
    };
    struct {
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v1;
        CData/*4:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v1;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v2;
        CData/*4:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v2;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v3;
        CData/*4:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v3;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v4;
        CData/*4:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v4;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v5;
        CData/*4:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v5;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v6;
        CData/*4:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v6;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v7;
        CData/*4:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v7;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v8;
        CData/*4:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v8;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v9;
        CData/*4:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v9;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v10;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v11;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exception__v0;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exception__v1;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exception__v2;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_badvaddr__v0;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_badvaddr__v1;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_badvaddr__v2;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v0;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v1;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v2;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v3;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v4;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v5;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v6;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v7;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v8;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v9;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v10;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v11;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v12;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v13;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v14;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v15;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v16;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v17;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v18;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v19;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v20;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v21;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v22;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v23;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v24;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v25;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v26;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v27;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v28;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v29;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v30;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v31;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v32;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v33;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v34;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v35;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_uop__v1;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v12;
    };
    struct {
        CData/*0:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v11;
        CData/*4:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v11;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v13;
        CData/*4:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v12;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v14;
        CData/*4:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v13;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v15;
        CData/*4:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v14;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v16;
        CData/*4:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v15;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v17;
        CData/*4:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v16;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v18;
        CData/*4:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v17;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v19;
        CData/*4:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v18;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v20;
        CData/*4:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v19;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v21;
        CData/*4:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe__v20;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v22;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy__v23;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exception__v3;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exception__v4;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exception__v5;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_badvaddr__v3;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_badvaddr__v4;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_badvaddr__v5;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v36;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v37;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v38;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v39;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v40;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v41;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v42;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v43;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v44;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v45;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v46;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v47;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v48;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v49;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v50;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v51;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v52;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v53;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v54;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v55;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v56;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v57;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v58;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v59;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v60;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v61;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v62;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v63;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v64;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v65;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v66;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v67;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v68;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v69;
        CData/*4:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v70;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v70;
    };
    struct {
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val__v71;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_cause__v3;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_cause__v4;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_cause__v5;
        CData/*5:0*/ __VdlyDim0__core_top_contract_test_top__DOT__dut__DOT__core__DOT__iregfile__DOT__rf__v0;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__iregfile__DOT__rf__v0;
        CData/*5:0*/ __VdlyDim0__core_top_contract_test_top__DOT__dut__DOT__core__DOT__iregfile__DOT__rf__v1;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__iregfile__DOT__rf__v1;
        CData/*5:0*/ __VdlyDim0__core_top_contract_test_top__DOT__dut__DOT__core__DOT__iregfile__DOT__rf__v2;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__iregfile__DOT__rf__v2;
        CData/*5:0*/ __VdlyDim0__core_top_contract_test_top__DOT__dut__DOT__core__DOT__iregfile__DOT__rf__v3;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__iregfile__DOT__rf__v3;
        CData/*5:0*/ __VdlyDim0__core_top_contract_test_top__DOT__dut__DOT__core__DOT__iregfile__DOT__rf__v4;
        CData/*0:0*/ __VdlySet__core_top_contract_test_top__DOT__dut__DOT__core__DOT__iregfile__DOT__rf__v4;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__imem_req_ready__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__imem_resp_valid__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__dmem_req_ready__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__dmem_resp_valid__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__dmem_resp_is_store__0;
        CData/*5:0*/ __Vtrigprevexpr___TOP__dmem_resp_idx__0;
        CData/*7:0*/ __Vtrigprevexpr___TOP__hw_irq__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__ipi_irq__0;
        CData/*0:0*/ __VicoDidInit;
        CData/*0:0*/ __VicoPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_n__1;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        SData/*15:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__entry_commiting;
        SData/*15:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__entry_killed;
        SData/*15:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__entry_killed;
        SData/*13:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__pending_addr_q;
        SData/*11:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_iq__DOT__slot_valid;
        SData/*11:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_iq__DOT__slot_killed;
        SData/*11:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_iq__DOT__slot_grant;
        SData/*15:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__mem_iq__DOT__slot_valid;
        SData/*15:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__mem_iq__DOT__slot_killed;
        SData/*15:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__mem_iq__DOT__slot_grant;
        SData/*15:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__alu_iq__DOT__slot_valid;
        SData/*15:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__alu_iq__DOT__slot_killed;
        SData/*15:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__alu_iq__DOT__slot_grant;
        SData/*14:0*/ __VdfgRegularize_h6e95ff9d_0_92;
        SData/*12:0*/ __VdfgRegularize_h6e95ff9d_0_198;
        SData/*11:0*/ __VdfgRegularize_h6e95ff9d_0_205;
        SData/*11:0*/ __VdfgRegularize_h6e95ff9d_0_206;
        SData/*11:0*/ __VdfgRegularize_h6e95ff9d_0_256;
        SData/*9:0*/ __VdfgRegularize_h6e95ff9d_0_259;
        SData/*11:0*/ __VdfgRegularize_h6e95ff9d_0_262;
        SData/*9:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_cause__v0;
        SData/*9:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_cause__v1;
        SData/*13:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_uop__v0;
        SData/*9:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_badvaddr__v0;
        SData/*9:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_badvaddr__v1;
        SData/*13:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_uop__v1;
        SData/*9:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_badvaddr__v3;
        SData/*9:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_badvaddr__v4;
        SData/*9:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_cause__v3;
        SData/*9:0*/ __VdlyLsb__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_cause__v4;
        VL_OUT(imem_req_addr,31,0);
        VL_INW(imem_resp_insts,127,0,4);
    };
    struct {
        VL_OUT(dmem_req_addr,31,0);
        VL_OUT(dmem_req_data,31,0);
        VL_IN(dmem_resp_data,31,0);
        VL_OUT64(commit_pc,63,0);
        VL_OUT64(commit_inst,63,0);
        VL_OUT(exception_pc,31,0);
        VL_OUT(exception_inst,31,0);
        VL_OUT(exception_cause,31,0);
        VL_OUT(exception_badvaddr,31,0);
        QData/*63:0*/ core_top_contract_test_top__DOT__dut__DOT__buffer_deq_pc;
        QData/*63:0*/ core_top_contract_test_top__DOT__dut__DOT__buffer_deq_insts;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core_redirect_pc;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_wdata;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__next_decode_pc_q;
        QData/*63:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__dec_pcs;
        QData/*63:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rn2_pc_q;
        VlWide<5>/*159:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rf_write_data;
        VlWide<15>/*450:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__mem_xcpt__BRA__450__03a0__KET__;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT____Vcellinp__unq_inst__src2_data;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_interrupt_next_pc_w;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__pipe_src1;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__pipe_src2;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__dividend_abs;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__divisor_abs;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__otfc_quotient;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__otfc_quotient_minus_one;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__quotient_result_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__remainder_result_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__ld_query_addr;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__ld_query_forward_data;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__req_hold_addr;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__req_hold_data;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__req_hold_addr;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__fwd_hold_data;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__unnamedblk17__DOT__unnamedblk18__DOT__slot;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__rrd_src1;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__rrd_src2;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__rrd_imm;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__exe_src1;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__exe_src2;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__exe_imm;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__alu_result;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__rrd_src1;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__rrd_src2;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__rrd_imm;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__exe_src1;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__exe_src2;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__exe_imm;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__alu_result;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__rrd_src1;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__rrd_src2;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__rrd_imm;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__exe_src1;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__exe_src2;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__exe_imm;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__alu_result;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__rrd_src1;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__rrd_src2;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__rrd_imm;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__exe_src1;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__exe_src2;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__exe_imm;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__eff_addr;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_29__write_mask;
    };
    struct {
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_28__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_27__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_26__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_25__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_24__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_23__merge_write;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_22__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_21__merge_write;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_20__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_19__merge_write;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_18__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_17__merge_write;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_16__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_15__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_14__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_13__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_12__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_11__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_10__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_9__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_8__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_7__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_6__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_5__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_4__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_3__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_2__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT____VlemCall_1__write_mask;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__crmd_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__prmd_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__euen_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__ecfg_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__estat_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__era_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__badv_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__eentry_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__tlbidx_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__tlbehi_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__tlbelo0_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__tlbelo1_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__asid_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__pgdl_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__pgdh_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__tid_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__tcfg_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__tval_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__llbctl_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__tlbrentry_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__dmw0_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__dmw1_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__badi_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__cntc_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__pending_wdata_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__pending_wmask_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__resp_data_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__pending_tcfg_write_value;
        VlWide<8>/*255:0*/ core_top_contract_test_top__DOT__dut__DOT__fetch_buffer__DOT__inst_mem;
        VlWide<8>/*255:0*/ core_top_contract_test_top__DOT__dut__DOT__fetch_buffer__DOT__pc_mem;
        VlWide<4>/*127:0*/ core_top_contract_test_top__DOT__dut__DOT__fetch_buffer__DOT__packed_enq_insts;
        VlWide<4>/*127:0*/ core_top_contract_test_top__DOT__dut__DOT__fetch_buffer__DOT__packed_enq_pcs;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__frontend__DOT____VlemCall_0__align_bundle;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__frontend__DOT__request_pc_q;
        IData/*31:0*/ core_top_contract_test_top__DOT__dut__DOT__frontend__DOT__redirect_pc_q;
        VlWide<4>/*127:0*/ core_top_contract_test_top__DOT__dut__DOT__frontend__DOT__fetch_pc_q;
    };
    struct {
        VlWide<4>/*127:0*/ core_top_contract_test_top__DOT__dut__DOT__frontend__DOT__fetch_insts_q;
        IData/*31:0*/ __Vfunc_core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__align_store_data__26__Vfuncout;
        IData/*31:0*/ __Vfunc_core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__align_store_data__26__data;
        IData/*31:0*/ __Vfunc_core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__align_store_data__26__addr;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_0;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_3;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_43;
        VlWide<13>/*410:0*/ __VdfgRegularize_h6e95ff9d_0_51;
        IData/*29:0*/ __VdfgRegularize_h6e95ff9d_0_60;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_70;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_276;
        VlWide<9>/*258:0*/ __VdfgRegularize_h6e95ff9d_0_283;
        IData/*31:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__otfc_quotient;
        IData/*31:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__otfc_quotient_minus_one;
        IData/*31:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__tval_q;
        IData/*31:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__estat_q;
        IData/*31:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__prmd_q;
        IData/*31:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__crmd_q;
        IData/*31:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__frontend__DOT__request_pc_q;
        IData/*31:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__frontend__DOT__redirect_pc_q;
        IData/*31:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__save_q__v0;
        IData/*31:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__save_q__v1;
        IData/*31:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__save_q__v2;
        IData/*31:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__save_q__v3;
        IData/*31:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_cause__v0;
        IData/*31:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_cause__v1;
        IData/*31:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_badvaddr__v1;
        IData/*31:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_badvaddr__v4;
        IData/*31:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_cause__v3;
        IData/*31:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_cause__v4;
        IData/*31:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__iregfile__DOT__rf__v0;
        IData/*31:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__iregfile__DOT__rf__v1;
        IData/*31:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__iregfile__DOT__rf__v2;
        IData/*31:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__iregfile__DOT__rf__v3;
        IData/*31:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__iregfile__DOT__rf__v4;
        VlWide<4>/*127:0*/ __Vtrigprevexpr___TOP__imem_resp_insts__0;
        IData/*31:0*/ __Vtrigprevexpr___TOP__dmem_resp_data__0;
        IData/*31:0*/ __VactIterCount;
        VlWide<26>/*821:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__dec_uops;
        QData/*63:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_counter_value_w;
        VlWide<26>/*821:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__dispatch_in_uops;
        VlWide<39>/*1232:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT____Vcellout__alu_iq__iss_uop;
        VlWide<13>/*410:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT____Vcellout__mem_iq__iss_uop;
        VlWide<13>/*410:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT____Vcellout__unq_iq__iss_uop;
        VlWide<26>/*821:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT____Vcellinp__lsu_inst__commit_uops;
        VlWide<85>/*2705:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_wb_resps;
        VlWide<5>/*143:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_com_xcpt_w;
        VlWide<16>/*491:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__brupdate_w;
        VlWide<13>/*410:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__pipe_uop;
        QData/*35:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__partial_q;
        QData/*35:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__divisor_q;
        QData/*35:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__partial_after_digit;
        QData/*47:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__mt_arch_busy_vec;
        VlWide<26>/*821:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__rn2_uops_q;
        VlWide<26>/*821:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__rn2_uops_next;
        QData/*47:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__busytable__DOT__busy_vec;
        VlWide<5>/*143:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT__alloc_suffix;
        QData/*47:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT__alloc_mask_all;
        QData/*47:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT__br_free_mask;
        QData/*47:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT__free_vec_next;
        QData/*47:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT__free_vec;
        VlWide<241>/*7711:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__entries;
        VlWide<31>/*963:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__enq_entries;
        VlWide<13>/*410:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__req_hold_uop;
    };
    struct {
        VlWide<224>/*7167:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__entries;
        VlWide<28>/*895:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__enq_entries;
        VlWide<13>/*410:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__req_hold_uop;
        VlWide<13>/*410:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__req_candidate_uop;
        VlWide<13>/*410:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__rrd_uop;
        VlWide<13>/*410:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__exe_uop;
        VlWide<13>/*410:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__rrd_uop;
        VlWide<13>/*410:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__exe_uop;
        VlWide<13>/*410:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__rrd_uop;
        VlWide<13>/*410:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__exe_uop;
        VlWide<13>/*410:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__rrd_uop;
        VlWide<13>/*410:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__exe_uop;
        QData/*63:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__stable_counter_q;
        VlWide<13>/*410:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__xcpt_uop;
        VlWide<155>/*4931:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_iq__DOT__slot_uop;
        VlWide<26>/*821:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_iq__DOT__dis_uop_updated;
        VlWide<206>/*6575:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__mem_iq__DOT__slot_uop;
        VlWide<26>/*821:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__mem_iq__DOT__dis_uop_updated;
        VlWide<206>/*6575:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__alu_iq__DOT__slot_uop;
        VlWide<26>/*821:0*/ core_top_contract_test_top__DOT__dut__DOT__core__DOT__alu_iq__DOT__dis_uop_updated;
        QData/*35:0*/ __VdfgRegularize_h6e95ff9d_0_93;
        QData/*63:0*/ __VdfgRegularize_h6e95ff9d_0_150;
        QData/*63:0*/ __VdfgRegularize_h6e95ff9d_0_152;
        QData/*35:0*/ __VdfgRegularize_h6e95ff9d_0_289;
        VlWide<13>/*410:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__pipe_uop;
        QData/*35:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_inst__DOT__divider_i__DOT__srt4_core_i__DOT__partial_q;
        VlWide<241>/*7711:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__store_queue_i__DOT__entries;
        VlWide<224>/*7167:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__lsu_inst__DOT__load_queue_i__DOT__entries;
        VlWide<155>/*4931:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__unq_iq__DOT__slot_uop;
        VlWide<206>/*6575:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__mem_iq__DOT__slot_uop;
        VlWide<206>/*6575:0*/ __Vdly__core_top_contract_test_top__DOT__dut__DOT__core__DOT__alu_iq__DOT__slot_uop;
        QData/*47:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT__br_alloc_q__v4;
        QData/*47:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT__br_alloc_q__v5;
        QData/*47:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT__br_alloc_q__v6;
        QData/*47:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT__br_alloc_q__v7;
        QData/*47:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT__br_alloc_q__v8;
        QData/*47:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT__br_alloc_q__v9;
        VlWide<13>/*410:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_uop__v0;
        VlWide<13>/*410:0*/ __VdlyVal__core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_uop__v1;
        VlUnpacked<QData/*47:0*/, 4> core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT__br_alloc_q;
        VlUnpacked<QData/*47:0*/, 2> core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__freelist__DOT__alloc_mask;
        VlUnpacked<CData/*5:0*/, 32> core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__maptable__DOT__map_q;
        VlUnpacked<CData/*5:0*/, 32> core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__maptable__DOT__commit_map_q;
        VlUnpacked<VlUnpacked<CData/*5:0*/, 32>, 4> core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__maptable__DOT__br_snapshot_q;
        VlUnpacked<VlUnpacked<CData/*5:0*/, 32>, 3> core_top_contract_test_top__DOT__dut__DOT__core__DOT__rename__DOT__maptable__DOT__map_after_lane;
        VlUnpacked<IData/*31:0*/, 4> core_top_contract_test_top__DOT__dut__DOT__core__DOT__csr_file_inst__DOT__save_q;
        VlUnpacked<IData/*31:0*/, 2> core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_val;
        VlUnpacked<IData/*31:0*/, 2> core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_bsy;
        VlUnpacked<IData/*31:0*/, 2> core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_unsafe;
        VlUnpacked<VlWide<411>/*13151:0*/, 2> core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_uop;
        VlUnpacked<VlWide<32>/*1023:0*/, 2> core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_wdata;
        VlUnpacked<IData/*31:0*/, 2> core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exception;
        VlUnpacked<IData/*31:0*/, 2> core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_predicated;
        VlUnpacked<VlWide<32>/*1023:0*/, 2> core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_cause;
        VlUnpacked<VlWide<32>/*1023:0*/, 2> core_top_contract_test_top__DOT__dut__DOT__core__DOT__rob_inst__DOT__rob_exc_badvaddr;
        VlUnpacked<IData/*31:0*/, 48> core_top_contract_test_top__DOT__dut__DOT__core__DOT__iregfile__DOT__rf;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 2> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };
    Vcore_top_contract_test_top_commit_signal_t__struct__0 core_top_contract_test_top__DOT__dut__DOT__core_commit;

    // INTERNAL VARIABLES
    Vcore_top_contract_test_top__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vcore_top_contract_test_top___024root(Vcore_top_contract_test_top__Syms* symsp, const char* namep);
    ~Vcore_top_contract_test_top___024root();
    VL_UNCOPYABLE(Vcore_top_contract_test_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
