module tlb_test_top #(
    parameter int NUM_ENTRIES = 8,
    parameter int IDX_W = (NUM_ENTRIES <= 1) ? 1 : $clog2(NUM_ENTRIES)
) (
    input  logic                 clk,
    input  logic                 rst_n,
    input  logic                 q0_valid,
    input  logic [31:0]          q0_vaddr,
    input  logic [9:0]           q0_asid,
    output logic                 q0_resp_valid,
    output logic                 q0_found,
    output logic [IDX_W-1:0]     q0_index,
    output logic [5:0]           q0_ps,
    output logic [19:0]          q0_ppn,
    output logic                 q0_v,
    output logic                 q0_d,
    output logic [1:0]           q0_mat,
    output logic [1:0]           q0_plv,
    input  logic                 q1_valid,
    input  logic [31:0]          q1_vaddr,
    input  logic [9:0]           q1_asid,
    output logic                 q1_resp_valid,
    output logic                 q1_found,
    output logic [IDX_W-1:0]     q1_index,
    output logic [5:0]           q1_ps,
    output logic [19:0]          q1_ppn,
    output logic                 q1_v,
    output logic                 q1_d,
    output logic [1:0]           q1_mat,
    output logic [1:0]           q1_plv,
    input  logic                 wr_valid,
    input  logic [IDX_W-1:0]     wr_index,
    input  logic                 wr_e,
    input  logic [18:0]          wr_vppn,
    input  logic [9:0]           wr_asid,
    input  logic                 wr_g,
    input  logic [5:0]           wr_ps,
    input  logic [19:0]          wr_ppn0,
    input  logic [1:0]           wr_plv0,
    input  logic [1:0]           wr_mat0,
    input  logic                 wr_d0,
    input  logic                 wr_v0,
    input  logic [19:0]          wr_ppn1,
    input  logic [1:0]           wr_plv1,
    input  logic [1:0]           wr_mat1,
    input  logic                 wr_d1,
    input  logic                 wr_v1,
    input  logic [IDX_W-1:0]     rd_index,
    output logic                 rd_e,
    output logic [18:0]          rd_vppn,
    output logic [9:0]           rd_asid,
    output logic                 rd_g,
    output logic [5:0]           rd_ps,
    output logic [19:0]          rd_ppn0,
    output logic [1:0]           rd_plv0,
    output logic [1:0]           rd_mat0,
    output logic                 rd_d0,
    output logic                 rd_v0,
    output logic [19:0]          rd_ppn1,
    output logic [1:0]           rd_plv1,
    output logic [1:0]           rd_mat1,
    output logic                 rd_d1,
    output logic                 rd_v1,
    input  logic                 inv_valid,
    input  logic [4:0]           inv_op,
    input  logic [9:0]           inv_asid,
    input  logic [31:0]          inv_vaddr
);

    tlb #(
        .NUM_ENTRIES  (NUM_ENTRIES),
        .TLB_IDX_WIDTH(IDX_W),
        .ASID_WIDTH   (10)
    ) dut (
        .clk,
        .rst_n,
        .q0_valid,
        .q0_vaddr,
        .q0_asid,
        .q0_resp_valid,
        .q0_found,
        .q0_idx        (q0_index),
        .q0_ps,
        .q0_ppn,
        .q0_v,
        .q0_d,
        .q0_mat,
        .q0_plv,
        .q1_valid,
        .q1_vaddr,
        .q1_asid,
        .q1_resp_valid,
        .q1_found,
        .q1_idx        (q1_index),
        .q1_ps,
        .q1_ppn,
        .q1_v,
        .q1_d,
        .q1_mat,
        .q1_plv,
        .wr_valid,
        .wr_idx        (wr_index),
        .wr_e,
        .wr_vppn,
        .wr_asid,
        .wr_g,
        .wr_ps,
        .wr_ppn0,
        .wr_ppn1,
        .wr_mat0,
        .wr_mat1,
        .wr_plv0,
        .wr_plv1,
        .wr_d0,
        .wr_d1,
        .wr_v0,
        .wr_v1,
        .rd_idx        (rd_index),
        .rd_e,
        .rd_vppn,
        .rd_asid,
        .rd_g,
        .rd_ps,
        .rd_ppn0,
        .rd_ppn1,
        .rd_mat0,
        .rd_mat1,
        .rd_plv0,
        .rd_plv1,
        .rd_d0,
        .rd_d1,
        .rd_v0,
        .rd_v1,
        .inv_valid,
        .inv_op,
        .inv_asid,
        .inv_vaddr
    );

endmodule
