// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vboom_core.h for the primary calling header

#ifndef VERILATED_VBOOM_CORE___024ROOT_H_
#define VERILATED_VBOOM_CORE___024ROOT_H_  // guard

#include "verilated.h"
#include "Vboom_core_loom_types.h"
class Vboom_core_decode;


class Vboom_core__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vboom_core___024root final {
  public:
    // CELLS
    Vboom_core_loom_types* __PVT__loom_types;
    Vboom_core_decode* __PVT__boom_core__DOT__gen_decode__BRA__0__KET____DOT__decode_inst;
    Vboom_core_decode* __PVT__boom_core__DOT__gen_decode__BRA__1__KET____DOT__decode_inst;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_IN8(fe_valid,3,0);
        VL_OUT8(fe_ready,0,0);
        VL_OUT8(lsu_agen_valid,0,0);
        VL_OUT8(lsu_dgen_valid,0,0);
        VL_IN8(lsu_resp_valid,0,0);
        VL_OUT8(csr_req_valid,0,0);
        VL_OUT8(csr_cmd,1,0);
        VL_OUT8(rob_empty,0,0);
        VL_OUT8(commit_valid_dbg,0,0);
        VL_OUT8(commit_ldst_dbg,4,0);
        VL_OUT8(rf_wr_en_dbg,0,0);
        VL_OUT8(rf_wr_pdst_dbg,5,0);
        VL_OUT8(rf_wr_ldst_dbg,4,0);
        VL_OUT8(alu_imm_sel_dbg,2,0);
        VL_OUT8(rob_ready_dbg,0,0);
        VL_OUT8(ren_stalls_dbg,1,0);
        VL_OUT8(rn2_mask_dbg,1,0);
        VL_OUT8(dis_fire_dbg,1,0);
        VL_OUT8(alu_iss_valid_dbg,2,0);
        VL_OUT8(alu_res_valid_dbg,2,0);
        VL_OUT8(rob_wb_valid_dbg,5,0);
        CData/*1:0*/ boom_core__DOT__dec_xcpts;
        CData/*7:0*/ boom_core__DOT__bm_br_mask;
        CData/*0:0*/ boom_core__DOT__iq_mem_dis_valid;
        CData/*0:0*/ boom_core__DOT__iq_alu_dis_valid;
        CData/*0:0*/ boom_core__DOT__iq_unq_dis_valid;
        CData/*1:0*/ boom_core__DOT__dis_fire;
        CData/*0:0*/ boom_core__DOT__alu_iq_dis_ready;
        CData/*0:0*/ boom_core__DOT__mem_iq_dis_ready;
        CData/*0:0*/ boom_core__DOT__unq_iq_dis_ready;
        CData/*2:0*/ boom_core__DOT__alu_iss_valid;
        CData/*1:0*/ boom_core__DOT__mem_iss_valid;
        CData/*0:0*/ boom_core__DOT__unq_iss_valid;
        CData/*2:0*/ boom_core__DOT__alu_slot_grant;
        CData/*1:0*/ boom_core__DOT__mem_slot_grant;
        CData/*0:0*/ boom_core__DOT__unq_slot_grant;
        CData/*5:0*/ boom_core__DOT__wakeup_valid_w;
        QData/*35:0*/ boom_core__DOT__wakeup_pdst_w;
        CData/*3:0*/ boom_core__DOT__resolve_mask;
        CData/*1:0*/ boom_core__DOT__rename__DOT__dec_fire;
        CData/*5:0*/ boom_core__DOT__rename__DOT__busytable__DOT__busy;
        CData/*5:0*/ boom_core__DOT__rename__DOT__busytable__DOT__wakeup_en;
        QData/*35:0*/ boom_core__DOT__rename__DOT__busytable__DOT__wakeup_preg;
        CData/*5:0*/ boom_core__DOT__rename__DOT__freelist__DOT____VlemCall_0__priority_encoder;
        CData/*1:0*/ boom_core__DOT__rename__DOT__freelist__DOT__free_en;
        SData/*11:0*/ boom_core__DOT__rename__DOT__freelist__DOT__free_preg;
        SData/*11:0*/ boom_core__DOT__rename__DOT__freelist__DOT__alloc_cand;
        CData/*1:0*/ boom_core__DOT__rename__DOT__maptable__DOT__write_en;
        SData/*9:0*/ boom_core__DOT__rename__DOT__maptable__DOT__write_lreg;
        SData/*11:0*/ boom_core__DOT__rename__DOT__maptable__DOT__write_preg;
        CData/*1:0*/ boom_core__DOT__rename__DOT__maptable__DOT__commit_en;
        SData/*9:0*/ boom_core__DOT__rename__DOT__maptable__DOT__commit_lreg;
        SData/*11:0*/ boom_core__DOT__rename__DOT__maptable__DOT__commit_preg;
        CData/*0:0*/ boom_core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__wakeup_valid;
        CData/*0:0*/ boom_core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__brinfo_valid;
        CData/*0:0*/ boom_core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__rrd_valid;
        CData/*0:0*/ boom_core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__exe_valid;
        CData/*0:0*/ boom_core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__cond_true;
        CData/*0:0*/ boom_core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__wakeup_valid;
        CData/*0:0*/ boom_core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__brinfo_valid;
        CData/*0:0*/ boom_core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__rrd_valid;
        CData/*0:0*/ boom_core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__exe_valid;
    };
    struct {
        CData/*0:0*/ boom_core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__cond_true;
        CData/*0:0*/ boom_core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__wakeup_valid;
        CData/*0:0*/ boom_core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__brinfo_valid;
        CData/*0:0*/ boom_core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__rrd_valid;
        CData/*0:0*/ boom_core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__exe_valid;
        CData/*0:0*/ boom_core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__cond_true;
        CData/*0:0*/ boom_core__DOT__gen_mem__BRA__1__KET____DOT__mem_inst__DOT__rrd_valid;
        CData/*0:0*/ boom_core__DOT__gen_mem__BRA__1__KET____DOT__mem_inst__DOT__exe_valid;
        CData/*0:0*/ boom_core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__rrd_valid;
        CData/*0:0*/ boom_core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__exe_valid;
        CData/*0:0*/ boom_core__DOT__rob_inst__DOT____VlemCall_23__priority_encoder;
        CData/*4:0*/ boom_core__DOT__rob_inst__DOT____VlemCall_22__get_row;
        CData/*0:0*/ boom_core__DOT__rob_inst__DOT____VlemCall_21__is_older;
        CData/*4:0*/ boom_core__DOT__rob_inst__DOT____VlemCall_17__get_row;
        CData/*4:0*/ boom_core__DOT__rob_inst__DOT____VlemCall_16__get_row;
        CData/*4:0*/ boom_core__DOT__rob_inst__DOT____VlemCall_15__get_row;
        CData/*0:0*/ boom_core__DOT__rob_inst__DOT____VlemCall_14__get_bank;
        CData/*4:0*/ boom_core__DOT__rob_inst__DOT____VlemCall_13__get_row;
        CData/*0:0*/ boom_core__DOT__rob_inst__DOT____VlemCall_12__get_bank;
        CData/*0:0*/ boom_core__DOT__rob_inst__DOT____VlemCall_11__is_older;
        CData/*4:0*/ boom_core__DOT__rob_inst__DOT____VlemCall_7__get_row;
        CData/*4:0*/ boom_core__DOT__rob_inst__DOT____VlemCall_6__get_row;
        CData/*4:0*/ boom_core__DOT__rob_inst__DOT____VlemCall_5__get_row;
        CData/*0:0*/ boom_core__DOT__rob_inst__DOT____VlemCall_4__get_bank;
        CData/*5:0*/ boom_core__DOT__rob_inst__DOT____VlemCall_2__find_oldest_unsafe;
        CData/*5:0*/ boom_core__DOT__rob_inst__DOT____VlemCall_1__find_oldest_unsafe;
        CData/*4:0*/ boom_core__DOT__rob_inst__DOT____VlemCall_0__get_row;
        CData/*5:0*/ boom_core__DOT__rob_inst__DOT__rob_tail_idx;
        CData/*0:0*/ boom_core__DOT__rob_inst__DOT__flush_frontend;
        CData/*5:0*/ boom_core__DOT__rob_inst__DOT__rob_head_idx;
        CData/*4:0*/ boom_core__DOT__rob_inst__DOT__rob_head;
        CData/*4:0*/ boom_core__DOT__rob_inst__DOT__rob_tail;
        CData/*4:0*/ boom_core__DOT__rob_inst__DOT__rob_pnr;
        CData/*0:0*/ boom_core__DOT__rob_inst__DOT__rob_head_lsb;
        CData/*0:0*/ boom_core__DOT__rob_inst__DOT__rob_tail_lsb;
        CData/*0:0*/ boom_core__DOT__rob_inst__DOT__rob_pnr_lsb;
        CData/*1:0*/ boom_core__DOT__rob_inst__DOT__rob_state;
        CData/*1:0*/ boom_core__DOT__rob_inst__DOT__next_rob_state;
        CData/*1:0*/ boom_core__DOT__rob_inst__DOT__rob_head_vals;
        CData/*1:0*/ boom_core__DOT__rob_inst__DOT__can_throw_exception;
        CData/*1:0*/ boom_core__DOT__rob_inst__DOT__will_commit;
        CData/*0:0*/ boom_core__DOT__rob_inst__DOT__exception_throw_d1;
        CData/*0:0*/ boom_core__DOT__rob_inst__DOT__exception_throw_d2;
        CData/*0:0*/ boom_core__DOT__unq_inst__DOT__res_valid;
        CData/*1:0*/ boom_core__DOT__unq_inst__DOT__state;
        CData/*1:0*/ boom_core__DOT__unq_inst__DOT__next_state;
        CData/*4:0*/ boom_core__DOT__unq_inst__DOT__busy_cnt;
        CData/*0:0*/ boom_core__DOT__unq_inst__DOT__busy_done;
        CData/*4:0*/ boom_core__DOT__iregfile__DOT__write_en;
        IData/*29:0*/ boom_core__DOT__iregfile__DOT__write_addr;
        CData/*3:0*/ boom_core__DOT__unq_iq__DOT__dis_slot;
        CData/*0:0*/ boom_core__DOT__unq_iq__DOT__unnamedblk1__DOT__port_used;
        CData/*3:0*/ boom_core__DOT__mem_iq__DOT__dis_slot;
        CData/*1:0*/ boom_core__DOT__mem_iq__DOT__unnamedblk1__DOT__port_used;
        CData/*3:0*/ boom_core__DOT__alu_iq__DOT__dis_slot;
        CData/*2:0*/ boom_core__DOT__alu_iq__DOT__unnamedblk1__DOT__port_used;
        CData/*1:0*/ boom_core__DOT__disp__DOT__iq_ready;
        CData/*0:0*/ boom_core__DOT__disp__DOT__block;
        CData/*1:0*/ boom_core__DOT__brmask__DOT__will_fire;
        CData/*3:0*/ boom_core__DOT__brmask__DOT__br_mask_q;
        CData/*7:0*/ boom_core__DOT__brmask__DOT__alloc_mask;
        CData/*3:0*/ boom_core__DOT__brmask__DOT__curr_mask;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_1;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_3;
    };
    struct {
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_5;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_6;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_7;
        CData/*5:0*/ __VdfgRegularize_h6e95ff9d_0_24;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_45;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_46;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_47;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_48;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_51;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_77;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_78;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_79;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_82;
        CData/*4:0*/ __VdfgRegularize_h6e95ff9d_0_93;
        CData/*3:0*/ __VdfgRegularize_h6e95ff9d_0_96;
        CData/*1:0*/ __VdfgRegularize_h6e95ff9d_0_102;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_105;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_106;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_107;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_108;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_110;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_111;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_112;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_113;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_115;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_116;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_117;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_118;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_120;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_121;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_122;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_123;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_125;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_126;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_127;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_128;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_130;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_131;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_132;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_133;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_135;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_136;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_137;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_138;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_140;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_141;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_142;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_143;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_145;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_146;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_147;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_148;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_149;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_150;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_151;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_152;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_153;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_155;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_178;
        CData/*4:0*/ __Vdly__boom_core__DOT__rob_inst__DOT__rob_head;
        CData/*4:0*/ __Vdly__boom_core__DOT__rob_inst__DOT__rob_tail;
        CData/*1:0*/ __Vdly__boom_core__DOT__rob_inst__DOT__rob_state;
        CData/*4:0*/ __Vdly__boom_core__DOT__unq_inst__DOT__busy_cnt;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v0;
    };
    struct {
        CData/*0:0*/ __VdlySet__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v0;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v1;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v2;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v3;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v4;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v5;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v6;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v7;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v8;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v9;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v10;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v11;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v12;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v13;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v14;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v15;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v16;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v17;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v18;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v19;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v20;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v21;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v22;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v23;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v24;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v25;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v26;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v27;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v28;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v29;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v30;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v31;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v32;
        CData/*4:0*/ __VdlyDim0__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v32;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v32;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v33;
        CData/*4:0*/ __VdlyDim0__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v33;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v33;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rename__DOT__maptable__DOT__map_q__v34;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__commit_map_q__v0;
        CData/*4:0*/ __VdlyDim0__boom_core__DOT__rename__DOT__maptable__DOT__commit_map_q__v0;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rename__DOT__maptable__DOT__commit_map_q__v0;
        CData/*5:0*/ __VdlyVal__boom_core__DOT__rename__DOT__maptable__DOT__commit_map_q__v1;
        CData/*4:0*/ __VdlyDim0__boom_core__DOT__rename__DOT__maptable__DOT__commit_map_q__v1;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rename__DOT__maptable__DOT__commit_map_q__v1;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rename__DOT__maptable__DOT__commit_map_q__v2;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_uop__v0;
        CData/*0:0*/ __VdlyVal__boom_core__DOT__rob_inst__DOT__rob_exception__v0;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_exception__v0;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_exception__v0;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_exception__v1;
        CData/*0:0*/ __VdlyVal__boom_core__DOT__rob_inst__DOT__rob_bsy__v0;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_bsy__v0;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_bsy__v0;
        CData/*0:0*/ __VdlyVal__boom_core__DOT__rob_inst__DOT__rob_unsafe__v0;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_unsafe__v0;
        CData/*0:0*/ __VdlyVal__boom_core__DOT__rob_inst__DOT__rob_predicated__v0;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_predicated__v0;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_bsy__v1;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_bsy__v1;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_unsafe__v1;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_predicated__v1;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_bsy__v2;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_bsy__v2;
    };
    struct {
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_unsafe__v2;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_predicated__v2;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_bsy__v3;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_bsy__v3;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_unsafe__v3;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_predicated__v3;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_bsy__v4;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_bsy__v4;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_unsafe__v4;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_predicated__v4;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_bsy__v5;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_bsy__v5;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_unsafe__v5;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_predicated__v5;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_bsy__v6;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_bsy__v6;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_unsafe__v6;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_predicated__v6;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_bsy__v7;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_bsy__v8;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v0;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v1;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v2;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v3;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v4;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v5;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v6;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v7;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v8;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v9;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v10;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v11;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v12;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v13;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v14;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v15;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v16;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v17;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v18;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v19;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v20;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v21;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v22;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v23;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v24;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v25;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v26;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v27;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v28;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v29;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v30;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v31;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v32;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v33;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v34;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v35;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v36;
        CData/*0:0*/ __VdlyVal__boom_core__DOT__rob_inst__DOT__rob_exception__v2;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_exception__v2;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_exception__v2;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_exception__v3;
        CData/*0:0*/ __VdlyVal__boom_core__DOT__rob_inst__DOT__rob_bsy__v9;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_bsy__v9;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_bsy__v9;
    };
    struct {
        CData/*0:0*/ __VdlyVal__boom_core__DOT__rob_inst__DOT__rob_unsafe__v8;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_unsafe__v8;
        CData/*0:0*/ __VdlyVal__boom_core__DOT__rob_inst__DOT__rob_predicated__v8;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_predicated__v8;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_bsy__v10;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_bsy__v10;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_unsafe__v9;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_predicated__v9;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_bsy__v11;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_bsy__v11;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_unsafe__v10;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_predicated__v10;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_bsy__v12;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_bsy__v12;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_unsafe__v11;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_predicated__v11;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_bsy__v13;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_bsy__v13;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_unsafe__v12;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_predicated__v12;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_bsy__v14;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_bsy__v14;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_unsafe__v13;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_predicated__v13;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_bsy__v15;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_bsy__v15;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_unsafe__v14;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_predicated__v14;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_bsy__v16;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_bsy__v17;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_uop__v1;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_val__v37;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v37;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v38;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v39;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v40;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v41;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v42;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v43;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v44;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v45;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v46;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v47;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v48;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v49;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v50;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v51;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v52;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v53;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v54;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v55;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v56;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v57;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v58;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v59;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v60;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v61;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v62;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v63;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v64;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v65;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v66;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v67;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v68;
    };
    struct {
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v69;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_val__v70;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v70;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v71;
        CData/*4:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_val__v72;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v72;
        CData/*0:0*/ __VdlySet__boom_core__DOT__rob_inst__DOT__rob_val__v73;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_n__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__fe_valid__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__lsu_resp_valid__0;
        CData/*0:0*/ __VicoDidInit;
        CData/*0:0*/ __VicoPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_n__1;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        VL_OUT16(csr_addr,13,0);
        SData/*15:0*/ boom_core__DOT__alu_slot_request;
        SData/*15:0*/ boom_core__DOT__mem_slot_request;
        SData/*11:0*/ boom_core__DOT__unq_slot_request;
        SData/*11:0*/ boom_core__DOT__unq_iq__DOT__slot_valid;
        SData/*11:0*/ boom_core__DOT__unq_iq__DOT__slot_killed;
        SData/*11:0*/ boom_core__DOT__unq_iq__DOT__slot_ready;
        SData/*11:0*/ boom_core__DOT__unq_iq__DOT__slot_grant;
        SData/*11:0*/ boom_core__DOT__unq_iq__DOT__unnamedblk1__DOT__available;
        SData/*15:0*/ boom_core__DOT__mem_iq__DOT__slot_valid;
        SData/*15:0*/ boom_core__DOT__mem_iq__DOT__slot_killed;
        SData/*15:0*/ boom_core__DOT__mem_iq__DOT__slot_ready;
        SData/*15:0*/ boom_core__DOT__mem_iq__DOT__slot_grant;
        SData/*15:0*/ boom_core__DOT__mem_iq__DOT__unnamedblk1__DOT__available;
        SData/*15:0*/ boom_core__DOT__alu_iq__DOT__slot_valid;
        SData/*15:0*/ boom_core__DOT__alu_iq__DOT__slot_killed;
        SData/*15:0*/ boom_core__DOT__alu_iq__DOT__slot_ready;
        SData/*15:0*/ boom_core__DOT__alu_iq__DOT__slot_grant;
        SData/*15:0*/ boom_core__DOT__alu_iq__DOT__unnamedblk1__DOT__available;
        SData/*11:0*/ __VdfgRegularize_h6e95ff9d_0_29;
        SData/*11:0*/ __VdfgRegularize_h6e95ff9d_0_30;
        SData/*11:0*/ __VdfgRegularize_h6e95ff9d_0_172;
        SData/*11:0*/ __VdfgRegularize_h6e95ff9d_0_183;
        SData/*11:0*/ __VdfgRegularize_h6e95ff9d_0_184;
        SData/*13:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_uop__v0;
        SData/*13:0*/ __VdlyLsb__boom_core__DOT__rob_inst__DOT__rob_uop__v1;
        VL_INW(fe_insts,127,0,4);
        VL_OUT(lsu_agen_addr,31,0);
        VL_OUT(lsu_dgen_data,31,0);
        VL_OUT(csr_wdata,31,0);
        VL_IN(csr_rdata,31,0);
        VL_OUT(debug_pc,31,0);
        VL_OUT(rf_wr_data_dbg,31,0);
        VL_OUT(alu_rs1_dbg,31,0);
        VL_OUT(alu_imm_dbg,31,0);
        VL_OUT(alu_imm_packed_dbg,25,0);
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__rrd_rs1;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__rrd_rs2;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__rrd_imm;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__exe_rs1;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__exe_rs2;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__exe_imm;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__alu_result;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__op1;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__op2;
    };
    struct {
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__rrd_rs1;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__rrd_rs2;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__rrd_imm;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__exe_rs1;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__exe_rs2;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__exe_imm;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__alu_result;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__op1;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__op2;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__rrd_rs1;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__rrd_rs2;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__rrd_imm;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__exe_rs1;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__exe_rs2;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__exe_imm;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__alu_result;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__op1;
        IData/*31:0*/ boom_core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__op2;
        IData/*31:0*/ boom_core__DOT__gen_mem__BRA__1__KET____DOT__mem_inst__DOT__rrd_rs1;
        IData/*31:0*/ boom_core__DOT__gen_mem__BRA__1__KET____DOT__mem_inst__DOT__rrd_rs2;
        IData/*31:0*/ boom_core__DOT__gen_mem__BRA__1__KET____DOT__mem_inst__DOT__rrd_imm;
        IData/*31:0*/ boom_core__DOT__gen_mem__BRA__1__KET____DOT__mem_inst__DOT__exe_rs1;
        IData/*31:0*/ boom_core__DOT__gen_mem__BRA__1__KET____DOT__mem_inst__DOT__exe_rs2;
        IData/*31:0*/ boom_core__DOT__gen_mem__BRA__1__KET____DOT__mem_inst__DOT__exe_imm;
        IData/*31:0*/ boom_core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__rrd_rs1;
        IData/*31:0*/ boom_core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__rrd_rs2;
        IData/*31:0*/ boom_core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__rrd_imm;
        IData/*31:0*/ boom_core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__exe_rs1;
        IData/*31:0*/ boom_core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__exe_rs2;
        IData/*31:0*/ boom_core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__exe_imm;
        IData/*31:0*/ boom_core__DOT__unq_inst__DOT__pipe_rs1;
        IData/*31:0*/ boom_core__DOT__unq_inst__DOT__pipe_rs2;
        VlWide<5>/*159:0*/ boom_core__DOT__iregfile__DOT__write_data;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_2;
        VlWide<9>/*261:0*/ __VdfgRegularize_h6e95ff9d_0_21;
        VlWide<9>/*261:0*/ __VdfgRegularize_h6e95ff9d_0_22;
        VlWide<8>/*255:0*/ __VdfgRegularize_h6e95ff9d_0_26;
        VlWide<8>/*255:0*/ __VdfgRegularize_h6e95ff9d_0_27;
        VlWide<9>/*257:0*/ __VdfgRegularize_h6e95ff9d_0_41;
        VlWide<9>/*257:0*/ __VdfgRegularize_h6e95ff9d_0_42;
        VlWide<3>/*83:0*/ __VdfgRegularize_h6e95ff9d_0_43;
        VlWide<3>/*83:0*/ __VdfgRegularize_h6e95ff9d_0_44;
        VlWide<8>/*240:0*/ __VdfgRegularize_h6e95ff9d_0_57;
        VlWide<8>/*240:0*/ __VdfgRegularize_h6e95ff9d_0_58;
        IData/*30:0*/ __VdfgRegularize_h6e95ff9d_0_61;
        IData/*30:0*/ __VdfgRegularize_h6e95ff9d_0_62;
        VlWide<3>/*83:0*/ __VdfgRegularize_h6e95ff9d_0_63;
        VlWide<3>/*83:0*/ __VdfgRegularize_h6e95ff9d_0_64;
        VlWide<9>/*260:0*/ __VdfgRegularize_h6e95ff9d_0_65;
        VlWide<9>/*260:0*/ __VdfgRegularize_h6e95ff9d_0_66;
        VlWide<15>/*449:0*/ __VdfgRegularize_h6e95ff9d_0_68;
        IData/*29:0*/ __VdfgRegularize_h6e95ff9d_0_69;
        IData/*17:0*/ __VdfgRegularize_h6e95ff9d_0_83;
        IData/*25:0*/ __VdfgRegularize_h6e95ff9d_0_85;
        IData/*25:0*/ __VdfgRegularize_h6e95ff9d_0_87;
        IData/*17:0*/ __VdfgRegularize_h6e95ff9d_0_88;
        IData/*25:0*/ __VdfgRegularize_h6e95ff9d_0_90;
        IData/*25:0*/ __VdfgRegularize_h6e95ff9d_0_92;
        VlWide<12>/*377:0*/ __VdfgRegularize_h6e95ff9d_0_94;
        VlWide<8>/*255:0*/ __VdfgRegularize_h6e95ff9d_0_97;
        VlWide<8>/*255:0*/ __VdfgRegularize_h6e95ff9d_0_99;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_104;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_109;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_114;
    };
    struct {
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_119;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_124;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_129;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_134;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_139;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_144;
        VlWide<8>/*255:0*/ __VdfgRegularize_h6e95ff9d_0_179;
        VlWide<8>/*255:0*/ __VdfgRegularize_h6e95ff9d_0_180;
        VlWide<3>/*86:0*/ __VdfgRegularize_h6e95ff9d_0_181;
        VlWide<3>/*86:0*/ __VdfgRegularize_h6e95ff9d_0_182;
        VlWide<3>/*85:0*/ __VdfgRegularize_h6e95ff9d_0_185;
        VlWide<3>/*85:0*/ __VdfgRegularize_h6e95ff9d_0_186;
        VlWide<4>/*127:0*/ __Vtrigprevexpr___TOP__fe_insts__0;
        IData/*31:0*/ __Vtrigprevexpr___TOP__csr_rdata__0;
        IData/*31:0*/ __VactIterCount;
        VL_OUTW(lsu_agen_uop,376,0,12);
        VL_OUTW(lsu_dgen_uop,376,0,12);
        VL_INW(lsu_resp,416,0,14);
        VlWide<72>/*2303:0*/ boom_core__DOT__wakeups;
        VlWide<24>/*753:0*/ boom_core__DOT____Vcellinp__rename__commit_uops;
        VlWide<12>/*376:0*/ boom_core__DOT__iq_mem_dis_uop;
        VlWide<12>/*376:0*/ boom_core__DOT__iq_alu_dis_uop;
        VlWide<12>/*376:0*/ boom_core__DOT__iq_unq_dis_uop;
        VlWide<36>/*1130:0*/ boom_core__DOT____Vcellout__alu_iq__iss_uop;
        VlWide<24>/*753:0*/ boom_core__DOT____Vcellout__mem_iq__iss_uop;
        VlWide<12>/*376:0*/ boom_core__DOT____Vcellout__unq_iq__iss_uop;
        VlWide<79>/*2501:0*/ boom_core__DOT__rob_wb_resps;
        VlWide<12>/*383:0*/ boom_core__DOT____Vcellout__gen_alu__BRA__0__KET____DOT__alu_inst__wakeup;
        VlWide<12>/*383:0*/ boom_core__DOT____Vcellout__gen_alu__BRA__1__KET____DOT__alu_inst__wakeup;
        VlWide<12>/*383:0*/ boom_core__DOT____Vcellout__gen_alu__BRA__2__KET____DOT__alu_inst__wakeup;
        VlWide<24>/*753:0*/ boom_core__DOT__rename__DOT__dec_uops;
        QData/*47:0*/ boom_core__DOT__rename__DOT__mt_arch_busy_vec;
        QData/*47:0*/ boom_core__DOT__rename__DOT__busytable__DOT__busy_vec;
        QData/*47:0*/ boom_core__DOT__rename__DOT__freelist__DOT__free_vec;
        QData/*47:0*/ boom_core__DOT__rename__DOT__freelist__DOT__unnamedblk2__DOT__taken_mask;
        VlWide<12>/*376:0*/ boom_core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__rrd_uop;
        VlWide<12>/*376:0*/ boom_core__DOT__gen_alu__BRA__2__KET____DOT__alu_inst__DOT__exe_uop;
        VlWide<12>/*376:0*/ boom_core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__rrd_uop;
        VlWide<12>/*376:0*/ boom_core__DOT__gen_alu__BRA__1__KET____DOT__alu_inst__DOT__exe_uop;
        VlWide<12>/*376:0*/ boom_core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__rrd_uop;
        VlWide<12>/*376:0*/ boom_core__DOT__gen_alu__BRA__0__KET____DOT__alu_inst__DOT__exe_uop;
        VlWide<12>/*376:0*/ boom_core__DOT__gen_mem__BRA__1__KET____DOT__mem_inst__DOT__rrd_uop;
        VlWide<12>/*376:0*/ boom_core__DOT__gen_mem__BRA__1__KET____DOT__mem_inst__DOT__exe_uop;
        VlWide<12>/*376:0*/ boom_core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__rrd_uop;
        VlWide<12>/*376:0*/ boom_core__DOT__gen_mem__BRA__0__KET____DOT__mem_inst__DOT__exe_uop;
        VlWide<3>/*78:0*/ boom_core__DOT__rob_inst__DOT__com_xcpt;
        VlWide<3>/*78:0*/ boom_core__DOT__rob_inst__DOT__flush;
        VlWide<12>/*376:0*/ boom_core__DOT__unq_inst__DOT__pipe_uop;
        VlWide<142>/*4523:0*/ boom_core__DOT__unq_iq__DOT__slot_uop;
        VlWide<189>/*6031:0*/ boom_core__DOT__mem_iq__DOT__slot_uop;
        VlWide<189>/*6031:0*/ boom_core__DOT__alu_iq__DOT__slot_uop;
        VlWide<24>/*753:0*/ boom_core__DOT__disp__DOT__rn2_uops;
        VlWide<15>/*457:0*/ boom_core__DOT__brmask__DOT__brupdate;
        QData/*38:0*/ __VdfgRegularize_h6e95ff9d_0_52;
        QData/*38:0*/ __VdfgRegularize_h6e95ff9d_0_53;
        VlWide<142>/*4523:0*/ __Vdly__boom_core__DOT__unq_iq__DOT__slot_uop;
        VlWide<189>/*6031:0*/ __Vdly__boom_core__DOT__mem_iq__DOT__slot_uop;
        VlWide<189>/*6031:0*/ __Vdly__boom_core__DOT__alu_iq__DOT__slot_uop;
        VlWide<12>/*376:0*/ __VdlyVal__boom_core__DOT__rob_inst__DOT__rob_uop__v0;
        VlWide<12>/*376:0*/ __VdlyVal__boom_core__DOT__rob_inst__DOT__rob_uop__v1;
        VlWide<14>/*416:0*/ __Vtrigprevexpr___TOP__lsu_resp__0;
        VlUnpacked<CData/*5:0*/, 32> boom_core__DOT__rename__DOT__maptable__DOT__map_q;
        VlUnpacked<CData/*5:0*/, 32> boom_core__DOT__rename__DOT__maptable__DOT__commit_map_q;
        VlUnpacked<IData/*31:0*/, 2> boom_core__DOT__rob_inst__DOT__rob_val;
    };
    struct {
        VlUnpacked<IData/*31:0*/, 2> boom_core__DOT__rob_inst__DOT__rob_bsy;
        VlUnpacked<IData/*31:0*/, 2> boom_core__DOT__rob_inst__DOT__rob_unsafe;
        VlUnpacked<VlWide<377>/*12063:0*/, 2> boom_core__DOT__rob_inst__DOT__rob_uop;
        VlUnpacked<IData/*31:0*/, 2> boom_core__DOT__rob_inst__DOT__rob_exception;
        VlUnpacked<IData/*31:0*/, 2> boom_core__DOT__rob_inst__DOT__rob_predicated;
        VlUnpacked<IData/*31:0*/, 48> boom_core__DOT__iregfile__DOT__rf;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 2> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
        VlUnpacked<CData/*0:0*/, 11> __Vm_traceActivity;
    };
    Vboom_core_commit_signal_t__struct__0 commit;

    // INTERNAL VARIABLES
    Vboom_core__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vboom_core___024root(Vboom_core__Syms* symsp, const char* namep);
    ~Vboom_core___024root();
    VL_UNCOPYABLE(Vboom_core___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
