// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vboom_core.h for the primary calling header

#include "Vboom_core__pch.h"

void Vboom_core___024root___nba_sequent__TOP__0(Vboom_core___024root* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__1__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__2__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__3__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__4__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__5__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__6__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__7__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__8__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__9__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__10__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__11__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__1__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__2__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__3__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__4__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__5__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__6__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__7__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__8__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__9__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__10__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__11__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__12__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__13__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__14__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__15__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__1__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__2__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__3__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__4__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__5__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__6__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__7__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__8__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__9__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__10__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__11__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__12__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__13__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__14__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__15__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core___024root___nba_sequent__TOP__1(Vboom_core___024root* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__1__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__2__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__3__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__4__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__5__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__6__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__7__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__8__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__9__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__10__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__11__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__12__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__13__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__14__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__15__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__1__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__2__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__3__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__4__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__5__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__6__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__7__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__8__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__9__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__10__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__11__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__1__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__2__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__3__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__4__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__5__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__6__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__7__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__8__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__9__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__10__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__11__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__12__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__13__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__14__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__15__KET____DOT__slot__1(Vboom_core_issue_slot* vlSelf);
void Vboom_core___024root___nba_comb__TOP__0(Vboom_core___024root* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__1__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__2__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__3__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__4__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__5__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__6__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__7__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__8__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__9__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__10__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__11__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__12__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__13__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__14__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__15__KET____DOT__slot__0(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core___024root___nba_sequent__TOP__4(Vboom_core___024root* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__1__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__2__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__3__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__4__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__5__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__6__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__7__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__8__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__9__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__10__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__11__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core___024root___ico_comb__TOP__3(Vboom_core___024root* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__1__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__2__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__3__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__4__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__5__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__6__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__7__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__8__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__9__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__10__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__11__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__12__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__13__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__14__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__15__KET____DOT__slot__0(Vboom_core_issue_slot* vlSelf);
void Vboom_core___024root___ico_comb__TOP__4(Vboom_core___024root* vlSelf);
void Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__1__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__2__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__3__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__4__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__5__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__6__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__7__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__8__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__9__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__10__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__11__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__12__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__13__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__14__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__15__KET____DOT__slot__1(Vboom_core_issue_slot__Iz1* vlSelf);
void Vboom_core___024root___ico_comb__TOP__6(Vboom_core___024root* vlSelf);
void Vboom_core___024root___nba_comb__TOP__5(Vboom_core___024root* vlSelf);
void Vboom_core___024root___ico_comb__TOP__8(Vboom_core___024root* vlSelf);
void Vboom_core___024root___ico_comb__TOP__9(Vboom_core___024root* vlSelf);
void Vboom_core___024root___ico_comb__TOP__10(Vboom_core___024root* vlSelf);
void Vboom_core___024root___nba_comb__TOP__9(Vboom_core___024root* vlSelf);
void Vboom_core___024root___nba_comb__TOP__10(Vboom_core___024root* vlSelf);
void Vboom_core___024root___nba_comb__TOP__11(Vboom_core___024root* vlSelf);

void Vboom_core___024root___eval_nba(Vboom_core___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vboom_core___024root___eval_nba\n"); );
    Vboom_core__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    if ((0x0000000000000100ULL & vlSelfRef.__VnbaTriggered[0U])) {
        Vboom_core___024root___nba_sequent__TOP__0(vlSelf);
        vlSelfRef.__Vm_traceActivity[21U] = 1U;
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__0__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__1__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__1__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__2__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__2__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__3__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__3__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__4__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__4__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__5__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__5__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__6__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__6__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__7__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__7__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__8__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__8__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__9__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__9__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__10__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__10__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__11__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__11__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__1__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__1__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__2__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__2__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__3__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__3__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__4__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__4__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__5__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__5__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__6__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__6__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__7__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__7__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__8__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__8__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__9__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__9__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__10__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__10__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__11__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__11__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__12__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__12__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__13__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__13__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__14__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__14__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__15__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__15__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__0__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__1__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__1__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__2__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__2__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__3__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__3__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__4__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__4__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__5__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__5__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__6__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__6__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__7__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__7__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__8__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__8__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__9__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__9__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__10__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__10__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__11__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__11__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__12__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__12__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__13__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__13__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__14__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__14__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__15__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__15__KET____DOT__slot));
    }
    if ((0x0000000000000300ULL & vlSelfRef.__VnbaTriggered[0U])) {
        Vboom_core___024root___nba_sequent__TOP__1(vlSelf);
        vlSelfRef.__Vm_traceActivity[22U] = 1U;
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__0__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__1__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__1__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__2__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__2__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__3__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__3__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__4__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__4__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__5__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__5__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__6__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__6__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__7__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__7__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__8__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__8__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__9__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__9__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__10__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__10__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__11__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__11__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__12__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__12__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__13__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__13__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__14__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__14__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_sequent__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__15__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__15__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__0__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__1__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__1__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__2__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__2__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__3__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__3__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__4__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__4__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__5__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__5__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__6__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__6__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__7__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__7__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__8__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__8__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__9__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__9__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__10__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__10__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__11__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__11__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__1__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__1__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__2__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__2__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__3__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__3__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__4__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__4__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__5__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__5__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__6__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__6__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__7__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__7__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__8__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__8__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__9__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__9__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__10__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__10__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__11__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__11__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__12__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__12__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__13__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__13__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__14__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__14__KET____DOT__slot));
        Vboom_core_issue_slot___nba_sequent__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__15__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__15__KET____DOT__slot));
        {
            // Inlined CFunc: _nba_sequent__TOP__2
            vlSelfRef.boom_core__DOT__rob_inst__DOT__rob_state 
                = vlSelfRef.__Vdly__boom_core__DOT__rob_inst__DOT__rob_state;
            vlSelfRef.__VdfgRegularize_h6e95ff9d_0_150 
                = ((0U != (IData)(vlSelfRef.boom_core__DOT__rob_inst__DOT__rob_state)) 
                   & (1U != (IData)(vlSelfRef.boom_core__DOT__rob_inst__DOT__rob_state)));
        }
    }
    if ((0x0000000000000100ULL & vlSelfRef.__VnbaTriggered[0U])) {
        {
            // Inlined CFunc: _nba_sequent__TOP__3
            vlSelfRef.boom_core__DOT__rob_inst__DOT__exception_throw_d2 
                = vlSelfRef.boom_core__DOT__rob_inst__DOT__exception_throw_d1;
            vlSelfRef.boom_core__DOT__rob_inst__DOT__exception_throw_d1 
                = ((~ ((IData)(vlSelfRef.__VdfgRegularize_h6e95ff9d_0_270) 
                       | (IData)(vlSelfRef.__VdfgRegularize_h6e95ff9d_0_272))) 
                   & (0U != (IData)(vlSelfRef.boom_core__DOT__rob_inst__DOT__can_throw_exception)));
        }
    }
    if ((0x0000000000000300ULL & vlSelfRef.__VnbaTriggered[0U])) {
        Vboom_core___024root___nba_comb__TOP__0(vlSelf);
        vlSelfRef.__Vm_traceActivity[23U] = 1U;
        Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__0__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__1__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__1__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__2__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__2__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__3__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__3__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__4__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__4__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__5__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__5__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__6__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__6__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__7__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__7__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__8__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__8__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__9__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__9__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__10__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__10__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__11__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__11__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__12__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__12__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__13__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__13__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__14__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__14__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___nba_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__15__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__15__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__0__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__1__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__2__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__3__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__4__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__5__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__6__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__7__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__8__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__9__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__10__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__11__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__1__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__2__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__3__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__4__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__5__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__6__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__7__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__8__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__9__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__10__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__11__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__12__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__13__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__14__KET____DOT__slot));
        Vboom_core_issue_slot___nba_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__15__KET____DOT__slot));
    }
    if ((0x0000000000000380ULL & vlSelfRef.__VnbaTriggered[0U])) {
        {
            // Inlined CFunc: _act_sequent__TOP__0
            vlSelfRef.boom_core__DOT__brmask__DOT__br_mask 
                = (((IData)(vlSelfRef.__VdfgRegularize_h6e95ff9d_0_219) 
                    << 4U) | (IData)(vlSelfRef.boom_core__DOT__brmask__DOT__resolved_mask));
        }
    }
    if ((0x0000000000000300ULL & vlSelfRef.__VnbaTriggered[0U])) {
        Vboom_core___024root___nba_sequent__TOP__4(vlSelf);
        vlSelfRef.__Vm_traceActivity[24U] = 1U;
    }
    if ((0x0000000000000310ULL & vlSelfRef.__VnbaTriggered[0U])) {
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__0__KET____DOT__slot));
        vlSelfRef.__Vm_traceActivity[25U] = 1U;
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__1__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__1__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__2__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__2__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__3__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__3__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__4__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__4__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__5__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__5__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__6__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__6__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__7__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__7__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__8__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__8__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__9__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__9__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__10__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__10__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__11__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__unq_iq__DOT__gen_slots__BRA__11__KET____DOT__slot));
        Vboom_core___024root___ico_comb__TOP__3(vlSelf);
    }
    if ((0x0000000000000304ULL & vlSelfRef.__VnbaTriggered[0U])) {
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__0__KET____DOT__slot));
        vlSelfRef.__Vm_traceActivity[26U] = 1U;
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__1__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__1__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__2__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__2__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__3__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__3__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__4__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__4__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__5__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__5__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__6__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__6__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__7__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__7__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__8__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__8__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__9__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__9__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__10__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__10__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__11__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__11__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__12__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__12__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__13__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__13__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__14__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__14__KET____DOT__slot));
        Vboom_core_issue_slot___ico_comb__TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__15__KET____DOT__slot__0((&vlSymsp->TOP__boom_core__DOT__alu_iq__DOT__gen_slots__BRA__15__KET____DOT__slot));
        Vboom_core___024root___ico_comb__TOP__4(vlSelf);
    }
    if ((0x0000000000000340ULL & vlSelfRef.__VnbaTriggered[0U])) {
        Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__0__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__0__KET____DOT__slot));
        vlSelfRef.__Vm_traceActivity[27U] = 1U;
        Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__1__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__1__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__2__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__2__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__3__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__3__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__4__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__4__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__5__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__5__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__6__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__6__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__7__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__7__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__8__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__8__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__9__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__9__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__10__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__10__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__11__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__11__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__12__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__12__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__13__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__13__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__14__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__14__KET____DOT__slot));
        Vboom_core_issue_slot__Iz1___ico_comb__TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__15__KET____DOT__slot__1((&vlSymsp->TOP__boom_core__DOT__mem_iq__DOT__gen_slots__BRA__15__KET____DOT__slot));
        Vboom_core___024root___ico_comb__TOP__6(vlSelf);
    }
    if ((0x0000000000000381ULL & vlSelfRef.__VnbaTriggered[0U])) {
        Vboom_core___024root___nba_comb__TOP__5(vlSelf);
        vlSelfRef.__Vm_traceActivity[28U] = 1U;
    }
    if ((0x00000000000003c1ULL & vlSelfRef.__VnbaTriggered[0U])) {
        Vboom_core___024root___ico_comb__TOP__8(vlSelf);
    }
    if ((0x0000000000000391ULL & vlSelfRef.__VnbaTriggered[0U])) {
        Vboom_core___024root___ico_comb__TOP__9(vlSelf);
    }
    if ((0x0000000000000385ULL & vlSelfRef.__VnbaTriggered[0U])) {
        Vboom_core___024root___ico_comb__TOP__10(vlSelf);
    }
    if ((0x00000000000003e1ULL & vlSelfRef.__VnbaTriggered[0U])) {
        Vboom_core___024root___nba_comb__TOP__9(vlSelf);
        vlSelfRef.__Vm_traceActivity[29U] = 1U;
    }
    if ((0x0000000000000399ULL & vlSelfRef.__VnbaTriggered[0U])) {
        Vboom_core___024root___nba_comb__TOP__10(vlSelf);
        vlSelfRef.__Vm_traceActivity[30U] = 1U;
    }
    if ((0x0000000000000387ULL & vlSelfRef.__VnbaTriggered[0U])) {
        Vboom_core___024root___nba_comb__TOP__11(vlSelf);
        vlSelfRef.__Vm_traceActivity[31U] = 1U;
    }
}

void Vboom_core___024root___trigger_orInto__act_vec_vec(VlUnpacked<QData/*63:0*/, 1> &out, const VlUnpacked<QData/*63:0*/, 1> &in) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vboom_core___024root___trigger_orInto__act_vec_vec\n"); );
    // Locals
    IData/*31:0*/ n;
    // Body
    n = 0U;
    do {
        out[n] = (out[n] | in[n]);
        n = ((IData)(1U) + n);
    } while ((0U >= n));
}

#ifdef VL_DEBUG
VL_ATTR_COLD void Vboom_core___024root___dump_triggers__act(const VlUnpacked<QData/*63:0*/, 1> &triggers, const std::string &tag);
#endif  // VL_DEBUG
bool Vboom_core___024root___trigger_anySet__act(const VlUnpacked<QData/*63:0*/, 1> &in);
void Vboom_core___024root___eval_act(Vboom_core___024root* vlSelf);

bool Vboom_core___024root___eval_phase__act(Vboom_core___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vboom_core___024root___eval_phase__act\n"); );
    Vboom_core__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Locals
    CData/*0:0*/ __VactExecute;
    // Body
    {
        // Inlined CFunc: _eval_triggers_vec__act
        vlSelfRef.__VactTriggered[0U] = (QData)((IData)(
                                                        (((((~ (IData)(vlSelfRef.rst_n)) 
                                                            & (IData)(vlSelfRef.__Vtrigprevexpr___TOP__rst_n__1)) 
                                                           << 9U) 
                                                          | (((IData)(vlSelfRef.clk) 
                                                              & (~ (IData)(vlSelfRef.__Vtrigprevexpr___TOP__clk__1))) 
                                                             << 8U)) 
                                                         | (((((((IData)(vlSelfRef.__VdfgRegularize_h6e95ff9d_0_219) 
                                                                 != (IData)(vlSelfRef.__Vtrigprevexpr___TOP____VdfgRegularize_h6e95ff9d_0_219__1)) 
                                                                << 3U) 
                                                               | (((IData)(vlSelfRef.boom_core__DOT__mem_iq__DOT__slot_grant) 
                                                                   != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__boom_core__DOT__mem_iq__DOT__slot_grant__1)) 
                                                                  << 2U)) 
                                                              | (((vlSelfRef.boom_core__DOT__mem_iq__DOT__src_valid 
                                                                   != vlSelfRef.__Vtrigprevexpr___TOP__boom_core__DOT__mem_iq__DOT__src_valid__1) 
                                                                  << 1U) 
                                                                 | ((IData)(vlSelfRef.boom_core__DOT__unq_iq__DOT__slot_grant) 
                                                                    != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__boom_core__DOT__unq_iq__DOT__slot_grant__1)))) 
                                                             << 4U) 
                                                            | (((((IData)(vlSelfRef.boom_core__DOT__unq_iq__DOT__src_valid) 
                                                                  != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__boom_core__DOT__unq_iq__DOT__src_valid__1)) 
                                                                 << 3U) 
                                                                | (((IData)(vlSelfRef.boom_core__DOT__alu_iq__DOT__slot_grant) 
                                                                    != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__boom_core__DOT__alu_iq__DOT__slot_grant__1)) 
                                                                   << 2U)) 
                                                               | (((vlSelfRef.boom_core__DOT__alu_iq__DOT__src_valid 
                                                                    != vlSelfRef.__Vtrigprevexpr___TOP__boom_core__DOT__alu_iq__DOT__src_valid__1) 
                                                                   << 1U) 
                                                                  | ((IData)(vlSelfRef.boom_core__DOT__brmask__DOT__br_tag) 
                                                                     != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__boom_core__DOT__brmask__DOT__br_tag__1))))))));
        vlSelfRef.__Vtrigprevexpr___TOP__boom_core__DOT__brmask__DOT__br_tag__1 
            = vlSelfRef.boom_core__DOT__brmask__DOT__br_tag;
        vlSelfRef.__Vtrigprevexpr___TOP__boom_core__DOT__alu_iq__DOT__src_valid__1 
            = vlSelfRef.boom_core__DOT__alu_iq__DOT__src_valid;
        vlSelfRef.__Vtrigprevexpr___TOP__boom_core__DOT__alu_iq__DOT__slot_grant__1 
            = vlSelfRef.boom_core__DOT__alu_iq__DOT__slot_grant;
        vlSelfRef.__Vtrigprevexpr___TOP__boom_core__DOT__unq_iq__DOT__src_valid__1 
            = vlSelfRef.boom_core__DOT__unq_iq__DOT__src_valid;
        vlSelfRef.__Vtrigprevexpr___TOP__boom_core__DOT__unq_iq__DOT__slot_grant__1 
            = vlSelfRef.boom_core__DOT__unq_iq__DOT__slot_grant;
        vlSelfRef.__Vtrigprevexpr___TOP__boom_core__DOT__mem_iq__DOT__src_valid__1 
            = vlSelfRef.boom_core__DOT__mem_iq__DOT__src_valid;
        vlSelfRef.__Vtrigprevexpr___TOP__boom_core__DOT__mem_iq__DOT__slot_grant__1 
            = vlSelfRef.boom_core__DOT__mem_iq__DOT__slot_grant;
        vlSelfRef.__Vtrigprevexpr___TOP____VdfgRegularize_h6e95ff9d_0_219__1 
            = vlSelfRef.__VdfgRegularize_h6e95ff9d_0_219;
        vlSelfRef.__Vtrigprevexpr___TOP__clk__1 = vlSelfRef.clk;
        vlSelfRef.__Vtrigprevexpr___TOP__rst_n__1 = vlSelfRef.rst_n;
        if (VL_UNLIKELY(((1U & (~ (IData)(vlSelfRef.__VactDidInit)))))) {
            vlSelfRef.__VactDidInit = 1U;
            vlSelfRef.__VactTriggered[0U] = (1ULL | vlSelfRef.__VactTriggered[0U]);
            vlSelfRef.__VactTriggered[0U] = (2ULL | vlSelfRef.__VactTriggered[0U]);
            vlSelfRef.__VactTriggered[0U] = (4ULL | vlSelfRef.__VactTriggered[0U]);
            vlSelfRef.__VactTriggered[0U] = (8ULL | vlSelfRef.__VactTriggered[0U]);
            vlSelfRef.__VactTriggered[0U] = (0x0000000000000010ULL 
                                             | vlSelfRef.__VactTriggered[0U]);
            vlSelfRef.__VactTriggered[0U] = (0x0000000000000020ULL 
                                             | vlSelfRef.__VactTriggered[0U]);
            vlSelfRef.__VactTriggered[0U] = (0x0000000000000040ULL 
                                             | vlSelfRef.__VactTriggered[0U]);
            vlSelfRef.__VactTriggered[0U] = (0x0000000000000080ULL 
                                             | vlSelfRef.__VactTriggered[0U]);
        }
    }
#ifdef VL_DEBUG
    if (VL_UNLIKELY(vlSymsp->_vm_contextp__->debug())) {
        Vboom_core___024root___dump_triggers__act(vlSelfRef.__VactTriggered, "act"s);
    }
#endif
    Vboom_core___024root___trigger_orInto__act_vec_vec(vlSelfRef.__VnbaTriggered, vlSelfRef.__VactTriggered);
    __VactExecute = Vboom_core___024root___trigger_anySet__act(vlSelfRef.__VactTriggered);
    if (__VactExecute) {
        Vboom_core___024root___eval_act(vlSelf);
    }
    return (__VactExecute);
}

void Vboom_core___024root___trigger_clear__act(VlUnpacked<QData/*63:0*/, 1> &out) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vboom_core___024root___trigger_clear__act\n"); );
    // Locals
    IData/*31:0*/ n;
    // Body
    n = 0U;
    do {
        out[n] = 0ULL;
        n = ((IData)(1U) + n);
    } while ((1U > n));
}

bool Vboom_core___024root___eval_phase__nba(Vboom_core___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vboom_core___024root___eval_phase__nba\n"); );
    Vboom_core__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Locals
    CData/*0:0*/ __VnbaExecute;
    // Body
    __VnbaExecute = Vboom_core___024root___trigger_anySet__act(vlSelfRef.__VnbaTriggered);
    if (__VnbaExecute) {
        Vboom_core___024root___eval_nba(vlSelf);
        Vboom_core___024root___trigger_clear__act(vlSelfRef.__VnbaTriggered);
    }
    return (__VnbaExecute);
}

#ifdef VL_DEBUG
VL_ATTR_COLD void Vboom_core___024root___dump_triggers__ico(const VlUnpacked<QData/*63:0*/, 2> &triggers, const std::string &tag);
#endif  // VL_DEBUG
bool Vboom_core___024root___eval_phase__ico(Vboom_core___024root* vlSelf);

void Vboom_core___024root___eval(Vboom_core___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vboom_core___024root___eval\n"); );
    Vboom_core__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Locals
    IData/*31:0*/ __VicoIterCount;
    IData/*31:0*/ __VnbaIterCount;
    // Body
    __VicoIterCount = 0U;
    do {
        if (VL_UNLIKELY(((0x00002710U < __VicoIterCount)))) {
#ifdef VL_DEBUG
            Vboom_core___024root___dump_triggers__ico(vlSelfRef.__VicoTriggered, "ico"s);
#endif
            VL_FATAL_MT("boom_core.sv", 5, "", "DIDNOTCONVERGE: Input combinational region did not converge after '--converge-limit' of 10000 tries");
        }
        __VicoIterCount = ((IData)(1U) + __VicoIterCount);
        vlSelfRef.__VicoPhaseResult = Vboom_core___024root___eval_phase__ico(vlSelf);
    } while (vlSelfRef.__VicoPhaseResult);
    __VnbaIterCount = 0U;
    do {
        if (VL_UNLIKELY(((0x00002710U < __VnbaIterCount)))) {
#ifdef VL_DEBUG
            Vboom_core___024root___dump_triggers__act(vlSelfRef.__VnbaTriggered, "nba"s);
#endif
            VL_FATAL_MT("boom_core.sv", 5, "", "DIDNOTCONVERGE: NBA region did not converge after '--converge-limit' of 10000 tries");
        }
        __VnbaIterCount = ((IData)(1U) + __VnbaIterCount);
        vlSelfRef.__VactIterCount = 0U;
        do {
            if (VL_UNLIKELY(((0x00002710U < vlSelfRef.__VactIterCount)))) {
#ifdef VL_DEBUG
                Vboom_core___024root___dump_triggers__act(vlSelfRef.__VactTriggered, "act"s);
#endif
                VL_FATAL_MT("boom_core.sv", 5, "", "DIDNOTCONVERGE: Active region did not converge after '--converge-limit' of 10000 tries");
            }
            vlSelfRef.__VactIterCount = ((IData)(1U) 
                                         + vlSelfRef.__VactIterCount);
            vlSelfRef.__VactPhaseResult = Vboom_core___024root___eval_phase__act(vlSelf);
        } while (vlSelfRef.__VactPhaseResult);
        vlSelfRef.__VnbaPhaseResult = Vboom_core___024root___eval_phase__nba(vlSelf);
    } while (vlSelfRef.__VnbaPhaseResult);
}

#ifdef VL_DEBUG
void Vboom_core___024root___eval_debug_assertions(Vboom_core___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vboom_core___024root___eval_debug_assertions\n"); );
    Vboom_core__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    if (VL_UNLIKELY(((vlSelfRef.clk & 0xfeU)))) {
        Verilated::overWidthError("clk");
    }
    if (VL_UNLIKELY(((vlSelfRef.rst_n & 0xfeU)))) {
        Verilated::overWidthError("rst_n");
    }
    if (VL_UNLIKELY(((vlSelfRef.fe_valid & 0xf0U)))) {
        Verilated::overWidthError("fe_valid");
    }
    if (VL_UNLIKELY(((vlSelfRef.lsu_resp_valid & 0xfeU)))) {
        Verilated::overWidthError("lsu_resp_valid");
    }
}
#endif  // VL_DEBUG
