// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vrename_test_top.h for the primary calling header

#include "Vrename_test_top__pch.h"

void Vrename_test_top___024root___eval_triggers_vec__ico__0(Vrename_test_top___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vrename_test_top___024root___eval_triggers_vec__ico__0\n"); );
    Vrename_test_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelfRef.__VicoTriggered[0U] = (QData)((IData)(
                                                    (((((((IData)(vlSelfRef.dis_fire) 
                                                          != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__dis_fire__0)) 
                                                         << 0x0000000cU) 
                                                        | ((((((IData)(vlSelfRef.dis_ready) 
                                                               != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__dis_ready__0)) 
                                                              << 3U) 
                                                             | (((IData)(vlSelfRef.br_mispredict_mask) 
                                                                 != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__br_mispredict_mask__0)) 
                                                                << 2U)) 
                                                            | ((((IData)(vlSelfRef.br_resolve_mask) 
                                                                 != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__br_resolve_mask__0)) 
                                                                << 1U) 
                                                               | ((IData)(vlSelfRef.br_mispredict_tag) 
                                                                  != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__br_mispredict_tag__0)))) 
                                                           << 8U)) 
                                                       | (((((((IData)(vlSelfRef.br_mispredict) 
                                                               != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__br_mispredict__0)) 
                                                              << 3U) 
                                                             | (((IData)(vlSelfRef.kill) 
                                                                 != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__kill__0)) 
                                                                << 2U)) 
                                                            | ((((IData)(vlSelfRef.rollback) 
                                                                 != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__rollback__0)) 
                                                                << 1U) 
                                                               | ((IData)(vlSelfRef.commit_stale_pdst) 
                                                                  != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__commit_stale_pdst__0)))) 
                                                           << 4U) 
                                                          | (((((IData)(vlSelfRef.commit_pdst) 
                                                                != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__commit_pdst__0)) 
                                                               << 3U) 
                                                              | (((IData)(vlSelfRef.commit_ldst) 
                                                                  != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__commit_ldst__0)) 
                                                                 << 2U)) 
                                                             | ((((IData)(vlSelfRef.commit_valid) 
                                                                  != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__commit_valid__0)) 
                                                                 << 1U) 
                                                                | ((IData)(vlSelfRef.wakeup_pdst) 
                                                                   != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__wakeup_pdst__0)))))) 
                                                      << 0x00000010U) 
                                                     | ((((((((IData)(vlSelfRef.wakeup_valid) 
                                                              != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__wakeup_valid__0)) 
                                                             << 3U) 
                                                            | (((IData)(vlSelfRef.in_br_tag_1) 
                                                                != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__in_br_tag_1__0)) 
                                                               << 2U)) 
                                                           | ((((IData)(vlSelfRef.in_allocate_brtag_1) 
                                                                != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__in_allocate_brtag_1__0)) 
                                                               << 1U) 
                                                              | ((IData)(vlSelfRef.in_br_tag_0) 
                                                                 != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__in_br_tag_0__0)))) 
                                                          << 0x0000000cU) 
                                                         | ((((((IData)(vlSelfRef.in_allocate_brtag_0) 
                                                                != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__in_allocate_brtag_0__0)) 
                                                               << 3U) 
                                                              | (((IData)(vlSelfRef.in_br_mask_1) 
                                                                  != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__in_br_mask_1__0)) 
                                                                 << 2U)) 
                                                             | ((((IData)(vlSelfRef.in_ldst_1) 
                                                                  != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__in_ldst_1__0)) 
                                                                 << 1U) 
                                                                | ((IData)(vlSelfRef.in_lsrc2_1) 
                                                                   != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__in_lsrc2_1__0)))) 
                                                            << 8U)) 
                                                        | (((((((IData)(vlSelfRef.in_lsrc1_1) 
                                                                != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__in_lsrc1_1__0)) 
                                                               << 3U) 
                                                              | (((IData)(vlSelfRef.in_br_mask_0) 
                                                                  != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__in_br_mask_0__0)) 
                                                                 << 2U)) 
                                                             | ((((IData)(vlSelfRef.in_ldst_0) 
                                                                  != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__in_ldst_0__0)) 
                                                                 << 1U) 
                                                                | ((IData)(vlSelfRef.in_lsrc2_0) 
                                                                   != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__in_lsrc2_0__0)))) 
                                                            << 4U) 
                                                           | (((((IData)(vlSelfRef.in_lsrc1_0) 
                                                                 != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__in_lsrc1_0__0)) 
                                                                << 3U) 
                                                               | (((IData)(vlSelfRef.in_valid) 
                                                                   != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__in_valid__0)) 
                                                                  << 2U)) 
                                                              | ((((IData)(vlSelfRef.rst_n) 
                                                                   != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__rst_n__0)) 
                                                                  << 1U) 
                                                                 | ((IData)(vlSelfRef.clk) 
                                                                    != (IData)(vlSelfRef.__Vtrigprevexpr___TOP__clk__0)))))))));
}
